// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, ServerSentEventsResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CommandAgentLifecycleV2Data, CommandAgentLifecycleV2Errors, CommandAgentLifecycleV2Responses, CreateAgentApplicationV2Data, CreateAgentApplicationV2Errors, CreateAgentApplicationV2Responses, DecideAgentApplicationV2Data, DecideAgentApplicationV2Errors, DecideAgentApplicationV2Responses, GetAgentApplicationV2Data, GetAgentApplicationV2Errors, GetAgentApplicationV2Responses, GetAgentV2Data, GetAgentV2Errors, GetAgentV2Responses, GetConversationV2Data, GetConversationV2Errors, GetConversationV2Responses, GetDeploymentConfigurationV2Data, GetDeploymentConfigurationV2Errors, GetDeploymentConfigurationV2Responses, GetExecutionDetailV2Data, GetExecutionDetailV2Errors, GetExecutionDetailV2Responses, IssuePersonalApiCredentialV2Data, IssuePersonalApiCredentialV2Errors, IssuePersonalApiCredentialV2Responses, ListAdminAgentsV2Data, ListAdminAgentsV2Errors, ListAdminAgentsV2Responses, ListAgentApplicationsV2Data, ListAgentApplicationsV2Errors, ListAgentApplicationsV2Responses, ListAgentsV2Data, ListAgentsV2Errors, ListAgentsV2Responses, ListPendingAgentApplicationsV2Data, ListPendingAgentApplicationsV2Errors, ListPendingAgentApplicationsV2Responses, ListPlatformAuditV2Data, ListPlatformAuditV2Errors, ListPlatformAuditV2Responses, ListRecentPersonalConversationsV2Data, ListRecentPersonalConversationsV2Errors, ListRecentPersonalConversationsV2Responses, RevokePersonalApiCredentialV2Data, RevokePersonalApiCredentialV2Errors, RevokePersonalApiCredentialV2Responses, StreamConversationEventsV2Data, StreamConversationEventsV2Errors, StreamConversationEventsV2Response, StreamConversationEventsV2Responses, UpdateAgentApplicationV2Data, UpdateAgentApplicationV2Errors, UpdateAgentApplicationV2Responses, UpdateAgentConfigurationV2Data, UpdateAgentConfigurationV2Errors, UpdateAgentConfigurationV2Responses, WithdrawAgentApplicationV2Data, WithdrawAgentApplicationV2Errors, WithdrawAgentApplicationV2Responses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const listPendingAgentApplicationsV2 = <ThrowOnError extends boolean = false>(options?: Options<ListPendingAgentApplicationsV2Data, ThrowOnError>): RequestResult<ListPendingAgentApplicationsV2Responses, ListPendingAgentApplicationsV2Errors, ThrowOnError> => (options?.client ?? client).get<ListPendingAgentApplicationsV2Responses, ListPendingAgentApplicationsV2Errors, ThrowOnError>({ url: '/api/v2/admin/agent-applications', ...options });

export const decideAgentApplicationV2 = <ThrowOnError extends boolean = false>(options: Options<DecideAgentApplicationV2Data, ThrowOnError>): RequestResult<DecideAgentApplicationV2Responses, DecideAgentApplicationV2Errors, ThrowOnError> => (options.client ?? client).post<DecideAgentApplicationV2Responses, DecideAgentApplicationV2Errors, ThrowOnError>({
    url: '/api/v2/admin/agent-applications/{applicationId}/decision',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listAdminAgentsV2 = <ThrowOnError extends boolean = false>(options?: Options<ListAdminAgentsV2Data, ThrowOnError>): RequestResult<ListAdminAgentsV2Responses, ListAdminAgentsV2Errors, ThrowOnError> => (options?.client ?? client).get<ListAdminAgentsV2Responses, ListAdminAgentsV2Errors, ThrowOnError>({ url: '/api/v2/admin/agents', ...options });

export const listPlatformAuditV2 = <ThrowOnError extends boolean = false>(options?: Options<ListPlatformAuditV2Data, ThrowOnError>): RequestResult<ListPlatformAuditV2Responses, ListPlatformAuditV2Errors, ThrowOnError> => (options?.client ?? client).get<ListPlatformAuditV2Responses, ListPlatformAuditV2Errors, ThrowOnError>({ url: '/api/v2/admin/audit', ...options });

export const listAgentApplicationsV2 = <ThrowOnError extends boolean = false>(options?: Options<ListAgentApplicationsV2Data, ThrowOnError>): RequestResult<ListAgentApplicationsV2Responses, ListAgentApplicationsV2Errors, ThrowOnError> => (options?.client ?? client).get<ListAgentApplicationsV2Responses, ListAgentApplicationsV2Errors, ThrowOnError>({ url: '/api/v2/agent-applications', ...options });

export const createAgentApplicationV2 = <ThrowOnError extends boolean = false>(options: Options<CreateAgentApplicationV2Data, ThrowOnError>): RequestResult<CreateAgentApplicationV2Responses, CreateAgentApplicationV2Errors, ThrowOnError> => (options.client ?? client).post<CreateAgentApplicationV2Responses, CreateAgentApplicationV2Errors, ThrowOnError>({
    url: '/api/v2/agent-applications',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAgentApplicationV2 = <ThrowOnError extends boolean = false>(options: Options<GetAgentApplicationV2Data, ThrowOnError>): RequestResult<GetAgentApplicationV2Responses, GetAgentApplicationV2Errors, ThrowOnError> => (options.client ?? client).get<GetAgentApplicationV2Responses, GetAgentApplicationV2Errors, ThrowOnError>({ url: '/api/v2/agent-applications/{applicationId}', ...options });

export const updateAgentApplicationV2 = <ThrowOnError extends boolean = false>(options: Options<UpdateAgentApplicationV2Data, ThrowOnError>): RequestResult<UpdateAgentApplicationV2Responses, UpdateAgentApplicationV2Errors, ThrowOnError> => (options.client ?? client).put<UpdateAgentApplicationV2Responses, UpdateAgentApplicationV2Errors, ThrowOnError>({
    url: '/api/v2/agent-applications/{applicationId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const withdrawAgentApplicationV2 = <ThrowOnError extends boolean = false>(options: Options<WithdrawAgentApplicationV2Data, ThrowOnError>): RequestResult<WithdrawAgentApplicationV2Responses, WithdrawAgentApplicationV2Errors, ThrowOnError> => (options.client ?? client).post<WithdrawAgentApplicationV2Responses, WithdrawAgentApplicationV2Errors, ThrowOnError>({ url: '/api/v2/agent-applications/{applicationId}/withdraw', ...options });

export const listAgentsV2 = <ThrowOnError extends boolean = false>(options?: Options<ListAgentsV2Data, ThrowOnError>): RequestResult<ListAgentsV2Responses, ListAgentsV2Errors, ThrowOnError> => (options?.client ?? client).get<ListAgentsV2Responses, ListAgentsV2Errors, ThrowOnError>({ url: '/api/v2/agents', ...options });

export const getAgentV2 = <ThrowOnError extends boolean = false>(options: Options<GetAgentV2Data, ThrowOnError>): RequestResult<GetAgentV2Responses, GetAgentV2Errors, ThrowOnError> => (options.client ?? client).get<GetAgentV2Responses, GetAgentV2Errors, ThrowOnError>({ url: '/api/v2/agents/{agentId}', ...options });

export const updateAgentConfigurationV2 = <ThrowOnError extends boolean = false>(options: Options<UpdateAgentConfigurationV2Data, ThrowOnError>): RequestResult<UpdateAgentConfigurationV2Responses, UpdateAgentConfigurationV2Errors, ThrowOnError> => (options.client ?? client).put<UpdateAgentConfigurationV2Responses, UpdateAgentConfigurationV2Errors, ThrowOnError>({
    url: '/api/v2/agents/{agentId}/configuration',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const commandAgentLifecycleV2 = <ThrowOnError extends boolean = false>(options: Options<CommandAgentLifecycleV2Data, ThrowOnError>): RequestResult<CommandAgentLifecycleV2Responses, CommandAgentLifecycleV2Errors, ThrowOnError> => (options.client ?? client).post<CommandAgentLifecycleV2Responses, CommandAgentLifecycleV2Errors, ThrowOnError>({
    url: '/api/v2/agents/{agentId}/lifecycle',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getConversationV2 = <ThrowOnError extends boolean = false>(options: Options<GetConversationV2Data, ThrowOnError>): RequestResult<GetConversationV2Responses, GetConversationV2Errors, ThrowOnError> => (options.client ?? client).get<GetConversationV2Responses, GetConversationV2Errors, ThrowOnError>({ url: '/api/v2/conversations/{conversationId}', ...options });

export const streamConversationEventsV2 = <ThrowOnError extends boolean = false>(options: Options<StreamConversationEventsV2Data, ThrowOnError, StreamConversationEventsV2Response>): Promise<ServerSentEventsResult<StreamConversationEventsV2Responses>> => (options.client ?? client).sse.get<StreamConversationEventsV2Responses, StreamConversationEventsV2Errors, ThrowOnError>({ url: '/api/v2/conversations/{conversationId}/events', ...options });

export const getExecutionDetailV2 = <ThrowOnError extends boolean = false>(options: Options<GetExecutionDetailV2Data, ThrowOnError>): RequestResult<GetExecutionDetailV2Responses, GetExecutionDetailV2Errors, ThrowOnError> => (options.client ?? client).get<GetExecutionDetailV2Responses, GetExecutionDetailV2Errors, ThrowOnError>({ url: '/api/v2/conversations/{conversationId}/executions/{executionId}', ...options });

export const getDeploymentConfigurationV2 = <ThrowOnError extends boolean = false>(options?: Options<GetDeploymentConfigurationV2Data, ThrowOnError>): RequestResult<GetDeploymentConfigurationV2Responses, GetDeploymentConfigurationV2Errors, ThrowOnError> => (options?.client ?? client).get<GetDeploymentConfigurationV2Responses, GetDeploymentConfigurationV2Errors, ThrowOnError>({ url: '/api/v2/deployment/configuration', ...options });

/**
 * Issue a personal credential with one-time material delivery
 *
 * Active browser user only. Any Authorization header is rejected. Same-key replay returns the original current metadata and null material. Responses are no-store.
 */
export const issuePersonalApiCredentialV2 = <ThrowOnError extends boolean = false>(options: Options<IssuePersonalApiCredentialV2Data, ThrowOnError>): RequestResult<IssuePersonalApiCredentialV2Responses, IssuePersonalApiCredentialV2Errors, ThrowOnError> => (options.client ?? client).post<IssuePersonalApiCredentialV2Responses, IssuePersonalApiCredentialV2Errors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-platform-session',
            type: 'apiKey'
        }],
    url: '/api/v2/me/api-credentials',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke one credential owned by the current browser user
 *
 * Any Authorization header is rejected. Cross-person and missing credentials both return 404. No request body or identity overrides are accepted. Responses are no-store.
 */
export const revokePersonalApiCredentialV2 = <ThrowOnError extends boolean = false>(options: Options<RevokePersonalApiCredentialV2Data, ThrowOnError>): RequestResult<RevokePersonalApiCredentialV2Responses, RevokePersonalApiCredentialV2Errors, ThrowOnError> => (options.client ?? client).delete<RevokePersonalApiCredentialV2Responses, RevokePersonalApiCredentialV2Errors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-platform-session',
            type: 'apiKey'
        }],
    url: '/api/v2/me/api-credentials/{credentialId}',
    ...options
});

/**
 * Current personal Web conversation metadata ordered by updatedAt DESC, id DESC after authorization filtering
 */
export const listRecentPersonalConversationsV2 = <ThrowOnError extends boolean = false>(options?: Options<ListRecentPersonalConversationsV2Data, ThrowOnError>): RequestResult<ListRecentPersonalConversationsV2Responses, ListRecentPersonalConversationsV2Errors, ThrowOnError> => (options?.client ?? client).get<ListRecentPersonalConversationsV2Responses, ListRecentPersonalConversationsV2Errors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-platform-session',
            type: 'apiKey'
        }],
    url: '/api/v2/me/conversations/recent',
    ...options
});
