// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type PilotInternalErrorV1 = {
    code: 'INTERNAL_ERROR';
    message: string;
    retryable: true;
    schemaVersion: 1;
    traceId: string;
};

export type PilotProtocolErrorV1 = {
    code: 'AGENT_BUSY' | 'AGENT_STARTING' | 'AGENT_UPDATING' | 'RUNTIME_UNAVAILABLE' | 'CONNECTION_UNAVAILABLE' | 'PROVIDER_RATE_LIMITED' | 'DEPENDENCY_UNAVAILABLE' | 'INTERNAL_ERROR';
    message: string;
    retryable: true;
    schemaVersion: 1;
    traceId: string;
} | {
    code: 'INVALID_REQUEST' | 'AUTHENTICATION_REQUIRED' | 'RESOURCE_UNAVAILABLE' | 'AUTHORIZATION_REVOKED' | 'CONVERSATION_UNAVAILABLE' | 'EXECUTION_FAILED' | 'MODEL_SELECTION_INVALID' | 'CONNECTION_AUTHORIZATION_REQUIRED' | 'ACTION_UNAVAILABLE' | 'PROVIDER_REJECTED' | 'DELEGATED_RESULT_REJECTED' | 'ORIGINAL_RESPONSE_NOT_STARTED' | 'ORIGINAL_RESPONSE_ALREADY_FINISHED';
    message: string;
    retryable: false;
    schemaVersion: 1;
    traceId: string;
};

export type PlatformAuditProjectionV2 = {
    action: string;
    actor: {
        displayName: string;
        roles: Array<'employee' | 'system_admin'>;
        userId: string;
    } | {
        actorId: string;
        kind: 'system';
    };
    auditId: string;
    occurredAt: string;
    result: 'succeeded' | 'failed';
    schemaVersion: 2;
    subjectId: string;
    subjectType: 'agent_application' | 'agent' | 'configuration' | 'grant';
    summary: string;
    traceId: string;
};

export type ListPlatformAuditV2Data = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/api/v2/admin/audit';
};

export type ListPlatformAuditV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type ListPlatformAuditV2Error = ListPlatformAuditV2Errors[keyof ListPlatformAuditV2Errors];

export type ListPlatformAuditV2Responses = {
    /**
     * Platform audit
     */
    200: {
        items: Array<PlatformAuditProjectionV2>;
        nextCursor: string | null;
    };
};

export type ListPlatformAuditV2Response = ListPlatformAuditV2Responses[keyof ListPlatformAuditV2Responses];
