// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AgentApiCreationRequestV1 = {
    availability: Array<{
        kind: 'user';
        userId: string;
    } | {
        kind: 'organization';
        organizationId: string;
    }>;
    coOwnerIds: Array<string>;
    description: string;
    environment: Array<{
        name: string;
        value: string;
    }>;
    name: string;
    schemaVersion: 2;
    secrets: Array<{
        name: string;
    }>;
    source: {
        identityResponsibility: 'self-managed' | 'platform-managed';
        imageReference: string;
        interactionMode: 'self-managed';
        kind: 'custom';
    } | {
        imageReference: string;
        interactionMode: 'platform-adapter';
        kind: 'custom';
    };
} | {
    availability: Array<{
        kind: 'user';
        userId: string;
    } | {
        kind: 'organization';
        organizationId: string;
    }>;
    coOwnerIds: Array<string>;
    description: string;
    environment: Array<{
        name: string;
        value: string;
    }>;
    modelConfiguration: {
        defaultOptionId: string;
        defaultReasoningLevel: string;
        options: Array<{
            endpointId: string;
            modelId: string;
            optionId: string;
            reasoningLevels: Array<string>;
        }>;
    };
    name: string;
    schemaVersion: 3;
    secrets: Array<{
        name: string;
    }>;
    source: {
        kind: 'standard';
        templateId: string;
    };
};

export type AgentApiCreationResponseV1 = {
    agentId: string;
    replayed: boolean;
    revision: number;
    schemaVersion: 1;
    status: 'creating' | 'available' | 'stopped' | 'creation_failed' | 'disabled';
};

export type AgentApiLifecycleRequestV1 = {
    command: 'start' | 'stop' | 'restart';
    schemaVersion: 1;
};

export type AgentApiLifecycleResponseV1 = {
    agentId: string;
    replayed: boolean;
    revision: number;
    schemaVersion: 1;
    status: 'available' | 'stopped';
};

export type AgentApiStateResponseV1 = {
    agentId: string;
    revision: number;
    schemaVersion: 1;
    serviceAvailability: 'ready' | 'starting' | 'updating' | 'unavailable' | null;
    status: 'pending_approval' | 'withdrawn' | 'rejected' | 'creating' | 'available' | 'stopped' | 'creation_failed' | 'disabled';
};

export type AgentApplicationCreateRequestV2 = {
    availability: Array<{
        kind: 'user';
        userId: string;
    } | {
        kind: 'organization';
        organizationId: string;
    }>;
    coOwnerIds: Array<string>;
    description: string;
    environment: Array<{
        name: string;
        value: string;
    }>;
    modelConfiguration?: {
        defaultOptionId: string;
        defaultReasoningLevel: string;
        options: Array<{
            endpointId: string;
            modelId: string;
            optionId: string;
            reasoningLevels: Array<string>;
        }>;
    };
    name: string;
    schemaVersion: 2;
    secrets: Array<{
        name: string;
    }>;
    source: {
        kind: 'standard';
        templateId: string;
    } | {
        identityResponsibility: 'self-managed' | 'platform-managed';
        imageReference: string;
        interactionMode: 'self-managed';
        kind: 'custom';
    } | {
        imageReference: string;
        interactionMode: 'platform-adapter';
        kind: 'custom';
    };
};

export type AgentApplicationManagerRequestV1 = {
    schemaVersion: 1;
};

export type AgentApplicationManagerResponseV1 = {
    agentId: string;
    applicationId: string;
    authorizationRevision: string | null;
    granted: boolean;
    replayed: boolean;
    schemaVersion: 1;
};

export type AgentApplicationProjectionV2 = {
    agentId: string | null;
    applicationId: string;
    configuration: AgentConfigurationProjectionV2;
    decision: {
        decidedAt: string;
        reason: string | null;
    } | null;
    description: string;
    name: string;
    resourceProfile: {
        displayName: string;
        estimatedResources: {
            cpuMillicores: number;
            memoryMiB: number;
            storageGiB: number;
        };
        profileId: string;
    };
    schemaVersion: 2;
    source: {
        kind: 'standard';
        templateId: string;
    } | {
        identityResponsibility: 'self-managed' | 'platform-managed';
        imageReference: string;
        interactionMode: 'self-managed';
        kind: 'custom';
    } | {
        imageReference: string;
        interactionMode: 'platform-adapter';
        kind: 'custom';
    };
    status: 'pending_approval' | 'withdrawn' | 'rejected' | 'creating' | 'available' | 'stopped' | 'creation_failed' | 'disabled';
    submittedAt: string;
};

export type AgentApplicationUpdateRequestV2 = {
    availability: Array<{
        kind: 'user';
        userId: string;
    } | {
        kind: 'organization';
        organizationId: string;
    }>;
    coOwnerIds: Array<string>;
    description: string;
    environment: Array<{
        name: string;
        value: string;
    }>;
    modelConfiguration?: {
        defaultOptionId: string;
        defaultReasoningLevel: string;
        options: Array<{
            endpointId: string;
            modelId: string;
            optionId: string;
            reasoningLevels: Array<string>;
        }>;
    };
    name: string;
    schemaVersion: 2;
    secrets?: Array<{
        name: string;
    }>;
    source: {
        kind: 'standard';
        templateId: string;
    } | {
        identityResponsibility: 'self-managed' | 'platform-managed';
        imageReference: string;
        interactionMode: 'self-managed';
        kind: 'custom';
    } | {
        imageReference: string;
        interactionMode: 'platform-adapter';
        kind: 'custom';
    };
};

export type AgentConfigurationProjectionV2 = {
    availability: Array<{
        kind: 'user';
        userId: string;
    } | {
        kind: 'organization';
        organizationId: string;
    }>;
    channels: Array<{
        kind: 'web' | 'wecom_bot' | 'wecom_app';
        status: 'available' | 'not_configured' | 'binding' | 'bound' | 'failed';
    }>;
    defaultModelOptionId: string | null;
    defaultReasoningLevel: string | null;
    environment: Array<{
        name: string;
        value: string;
    }>;
    modelOptions: Array<{
        displayName: string;
        modelId: string;
        optionId: string;
        reasoningLevels: Array<string>;
    }>;
    owners: Array<{
        displayName: string;
        roles: Array<'employee' | 'system_admin'>;
        userId: string;
    }>;
    secrets: Array<{
        isSet: boolean;
        name: string;
        version: number | null;
    }>;
};

export type AgentConfigurationUpdateRequestV2 = {
    availability?: Array<{
        kind: 'user';
        userId: string;
    } | {
        kind: 'organization';
        organizationId: string;
    }>;
    channels?: Array<{
        bindingReference: string;
        enabled: true;
        kind: 'wecom_bot' | 'wecom_app';
    } | {
        enabled: false;
        kind: 'wecom_bot' | 'wecom_app';
    }>;
    coOwnerIds?: Array<string>;
    environment?: Array<{
        name: string;
        value: string;
    }>;
    modelConfiguration?: {
        defaultOptionId: string;
        defaultReasoningLevel: string;
        options: Array<{
            endpointId: string;
            modelId: string;
            optionId: string;
            reasoningLevels: Array<string>;
        }>;
    };
    schemaVersion: 2;
    secrets?: Array<{
        name: string;
    }>;
};

export type AgentLifecycleCommandRequestV1 = {
    command: 'stop' | 'restart' | 'retry_creation' | 'disable';
    schemaVersion: 1;
} | {
    command: 'upgrade_custom_image';
    imageReference: string;
    schemaVersion: 1;
};

export type AgentProjectionV2 = {
    agentId: string;
    capabilities: {
        attachments: boolean;
        connection: boolean;
        modelSelection: boolean;
        resultFiles: boolean;
        skills?: Array<{
            manifestSha256: string;
            name: string;
            packageDigest: string;
            readOnly: true;
            schemaVersion: 1;
            version: string;
        }>;
        supplementaryInstruction: boolean;
    };
    configuration: AgentConfigurationProjectionV2;
    description: string;
    interactionUrl: string | null;
    managementStatus: 'pending_approval' | 'withdrawn' | 'rejected' | 'creating' | 'available' | 'stopped' | 'creation_failed' | 'disabled';
    name: string;
    schemaVersion: 2;
    serviceAvailability: 'ready' | 'starting' | 'updating' | 'unavailable' | null;
    source: {
        kind: 'standard';
        templateId: string;
    } | {
        identityResponsibility: 'self-managed' | 'platform-managed';
        imageReference: string;
        interactionMode: 'self-managed';
        kind: 'custom';
    } | {
        imageReference: string;
        interactionMode: 'platform-adapter';
        kind: 'custom';
    };
};

export type AgentUserUseRevokeRequestV1 = {
    expectedRevision: number;
    schemaVersion: 1;
};

export type AgentUserUseRevokeResponseV1 = {
    agentId: string;
    authorizationRevision: string | null;
    granted: false;
    replayed: boolean;
    schemaVersion: 1;
    userId: string;
};

export type ApplicationDisableRequestV1 = {
    status: 'disabled';
};

export type ApplicationMetadataV1 = {
    applicationId: string;
    authorizationRevision: string;
    createdAt: string;
    name: string;
    responsibleUserId: string;
    status: 'active' | 'disabled';
    updatedAt: string;
};

export type ApplicationRegistrationRequestV1 = {
    name: string;
};

export type ApplicationRegistrationResponseV1 = {
    metadata: ApplicationMetadataV1;
    replayed: boolean;
};

export type ApprovalDecisionRequestV1 = {
    decision: 'approve';
    schemaVersion: 1;
} | {
    decision: 'reject';
    reason: string;
    schemaVersion: 1;
};

export type AuthorizationRevokedSignalV1 = {
    error: {
        code: 'AUTHORIZATION_REVOKED';
        message: string;
        retryable: false;
        schemaVersion: 1;
        traceId: string;
    };
    kind: 'control';
    schemaVersion: 1;
    type: 'authorization.revoked';
};

export type ConversationDetailProjectionV2 = {
    conversation: {
        agentId: string;
        conversationId: string;
        createdAt: string;
        lastConversationCursor: string | null;
        schemaVersion: 1;
        selectedModelOptionId: string | null;
        selectedReasoningLevel: string | null;
        status: 'ready' | 'active' | 'unavailable';
        title: string | null;
        updatedAt: string;
    };
    events: Array<PersistedConversationEventV2>;
    messages: Array<{
        answerVersion: number | null;
        createdAt: string;
        error: null;
        executionId: string | null;
        isCurrentAnswer: boolean | null;
        messageId: string;
        replyToMessageId: string | null;
        role: 'user' | 'assistant';
        status: 'submitted' | 'processing' | 'completed' | 'cancelled';
        text: string;
    } | {
        answerVersion: number | null;
        createdAt: string;
        error: PilotProtocolErrorV1;
        executionId: string | null;
        isCurrentAnswer: boolean | null;
        messageId: string;
        replyToMessageId: string | null;
        role: 'user' | 'assistant';
        status: 'failed';
        text: string;
    }>;
    schemaVersion: 2;
    sessionAvailability?: 'preparing' | 'ready' | 'unavailable' | 'updating';
};

export type ConversationSseMessageV1 = PersistedConversationEventV1 | HeartbeatSignalV1 | TimelineReloadSignalV1 | AuthorizationRevokedSignalV1;

export type ConversationSseMessageV2 = PersistedConversationEventV2 | HeartbeatSignalV1 | TimelineReloadSignalV1 | AuthorizationRevokedSignalV1;

export type DeploymentConfigurationProjectionV2 = {
    modelCatalog: DeploymentModelCatalogProjectionV2;
    schemaVersion: 2;
    status: DeploymentConfigurationStatusV2;
    templates: Array<DeploymentTemplateProjectionV2>;
};

export type DeploymentConfigurationStatusV2 = 'populated' | 'empty' | 'unavailable' | 'stale';

export type DeploymentModelCatalogProjectionV2 = {
    endpoints: Array<DeploymentModelEndpointProjectionV2>;
    revision: string | null;
    status: DeploymentConfigurationStatusV2;
};

export type DeploymentModelEndpointProjectionV2 = {
    displayName: string;
    endpointId: string;
    models: Array<DeploymentModelProjectionV2>;
};

export type DeploymentModelProjectionV2 = {
    modelId: string;
    reasoningLevels: Array<string>;
};

export type DeploymentTemplateProjectionV2 = {
    allowedEnvironmentKeys: Array<string>;
    allowedSecretKeys: Array<string>;
    connectionEnabled: boolean;
    displayName: string;
    templateId: string;
};

export type ExecutionDetailProjectionV2 = {
    conversationId: string;
    error: null;
    events: Array<PersistedConversationEventV2>;
    executionId: string;
    finishedAt: string | null;
    processSummary: Array<{
        kind: 'status';
        occurredAt: string;
        status: 'submitted' | 'processing' | 'completed' | 'failed' | 'cancelled' | 'unknown';
        summary: string;
    } | {
        kind: 'model_call';
        modelId: string;
        occurredAt: string;
        reasoningLevel: string | null;
        status: 'succeeded' | 'failed';
        summary: string;
    } | {
        accountDisplay: string;
        actionId: string;
        actionVersion: string;
        callId: string;
        kind: 'connection_call';
        occurredAt: string;
        providerId: string;
        status: 'succeeded' | 'failed';
        summary: string;
    } | {
        callId?: string;
        category: 'status' | 'model_call' | 'connection_call';
        kind: 'agent_summary';
        occurredAt: string;
        summary: string;
    }>;
    schemaVersion: 2;
    startedAt: string | null;
    status: 'submitted' | 'processing' | 'completed' | 'cancelled' | 'unknown';
} | {
    conversationId: string;
    error: PilotProtocolErrorV1;
    events: Array<PersistedConversationEventV2>;
    executionId: string;
    finishedAt: string | null;
    processSummary: Array<{
        kind: 'status';
        occurredAt: string;
        status: 'submitted' | 'processing' | 'completed' | 'failed' | 'cancelled' | 'unknown';
        summary: string;
    } | {
        kind: 'model_call';
        modelId: string;
        occurredAt: string;
        reasoningLevel: string | null;
        status: 'succeeded' | 'failed';
        summary: string;
    } | {
        accountDisplay: string;
        actionId: string;
        actionVersion: string;
        callId: string;
        kind: 'connection_call';
        occurredAt: string;
        providerId: string;
        status: 'succeeded' | 'failed';
        summary: string;
    } | {
        callId?: string;
        category: 'status' | 'model_call' | 'connection_call';
        kind: 'agent_summary';
        occurredAt: string;
        summary: string;
    }>;
    schemaVersion: 2;
    startedAt: string | null;
    status: 'failed';
};

export type ExecutionOperationEventV2 = {
    conversationCursor: string;
    conversationId: string;
    eventId: SseEventIdV1;
    executionId: string;
    kind: 'event';
    occurredAt: string;
    payload: RuntimeOperationFactV2;
    schemaVersion: 2;
    sequence: number;
    type: 'execution.operation';
};

export type HeartbeatSignalV1 = {
    kind: 'control';
    occurredAt: string;
    schemaVersion: 1;
    type: 'heartbeat';
};

export type ModelSelectionFallbackEventV1 = {
    conversationCursor: string;
    conversationId: string;
    eventId: SseEventIdV1;
    executionId: string;
    kind: 'event';
    occurredAt: string;
    payload: {
        modelOptionId: string;
        reason: 'selection_unavailable';
        reasoningLevel: string;
    };
    schemaVersion: 1;
    sequence: number;
    type: 'model.selection.fell_back';
};

export type PersistedConversationEventV1 = {
    conversationCursor: string;
    conversationId: string;
    eventId: SseEventIdV1;
    executionId: string;
    kind: 'event';
    occurredAt: string;
    payload: {
        text: string;
    };
    schemaVersion: 1;
    sequence: number;
    type: 'text.delta';
} | {
    conversationCursor: string;
    conversationId: string;
    eventId: SseEventIdV1;
    executionId: string;
    kind: 'event';
    occurredAt: string;
    payload: {
        status: 'submitted' | 'processing' | 'completed' | 'failed' | 'cancelled' | 'unknown';
    };
    schemaVersion: 1;
    sequence: number;
    type: 'execution.status';
} | {
    conversationCursor: string;
    conversationId: string;
    eventId: SseEventIdV1;
    executionId: string;
    kind: 'event';
    occurredAt: string;
    payload: {
        callId?: string;
        category: 'status' | 'model_call' | 'connection_call';
        summary: string;
    };
    schemaVersion: 1;
    sequence: number;
    type: 'execution.detail';
} | {
    conversationCursor: string;
    conversationId: string;
    eventId: SseEventIdV1;
    executionId: string;
    kind: 'event';
    occurredAt: string;
    payload: {
        fileId: string;
        mediaType: string;
        name: string;
        sizeBytes: number;
    };
    schemaVersion: 1;
    sequence: number;
    type: 'result.file';
} | {
    conversationCursor: string;
    conversationId: string;
    eventId: SseEventIdV1;
    executionId: string;
    kind: 'event';
    occurredAt: string;
    payload: {
        error: PilotProtocolErrorV1;
    };
    schemaVersion: 1;
    sequence: number;
    type: 'conversation.error';
} | ModelSelectionFallbackEventV1;

export type PersistedConversationEventV2 = PersistedConversationEventV1 | ExecutionOperationEventV2;

export type PersonalApiCredentialIssueRequestV1 = {
    expiresAt: string | null;
    scopes: Array<'agent:create' | 'agent:manage' | 'agent:use' | 'agent:read'>;
};

export type PersonalApiCredentialIssueResponseV1 = {
    /**
     * First committed delivery only; never persisted or replayed.
     */
    credential: string;
    metadata: PersonalApiCredentialMetadataV1;
    replayed: false;
} | {
    credential: null;
    metadata: PersonalApiCredentialMetadataV1;
    replayed: true;
};

export type PersonalApiCredentialListQueryV1 = {
    cursor?: string;
    limit?: number;
};

export type PersonalApiCredentialMetadataV1 = {
    createdAt: string;
    credentialId: string;
    expiresAt: string | null;
    lastUsedAt: string | null;
    revokedAt: string | null;
    scopes: Array<'agent:create' | 'agent:manage' | 'agent:use' | 'agent:read'>;
};

export type PersonalApiCredentialNarrowRequestV1 = {
    expiresAt?: string;
    scopes?: Array<'agent:create' | 'agent:manage' | 'agent:use' | 'agent:read'>;
};

export type PersonalApiCredentialNarrowResponseV1 = {
    metadata: PersonalApiCredentialMetadataV1;
    replayed: boolean;
};

export type PersonalApiCredentialPageV1 = {
    items: Array<PersonalApiCredentialMetadataV1>;
    nextCursor: string | null;
};

export type PersonalApiCredentialRevokeResponseV1 = {
    metadata: PersonalApiCredentialMetadataV1;
    replayed: boolean;
};

export type PersonalRelayKeyReplaceRequestV1 = {
    expectedVersion: number | null;
    /**
     * Write-only personal Relay Key; never returned or persisted as plaintext.
     */
    keyValue: string;
};

export type PersonalRelayKeyRevokeRequestV1 = {
    expectedVersion: number;
};

export type PersonalRelayKeyStateV1 = {
    isSet: false;
    keyVersion: null;
    schemaVersion: 1;
} | {
    isSet: true;
    keyVersion: number;
    schemaVersion: 1;
};

export type PilotInternalErrorV1 = {
    code: 'INTERNAL_ERROR';
    message: string;
    retryable: true;
    schemaVersion: 1;
    traceId: string;
};

export type PilotProtocolErrorV1 = {
    code: 'AGENT_BUSY' | 'AGENT_STARTING' | 'AGENT_UPDATING' | 'RUNTIME_UNAVAILABLE' | 'CONNECTION_UNAVAILABLE' | 'PROVIDER_RATE_LIMITED' | 'DEPENDENCY_UNAVAILABLE' | 'INTERNAL_ERROR';
    message: string;
    retryable: true;
    schemaVersion: 1;
    traceId: string;
} | {
    code: 'INVALID_REQUEST' | 'AUTHENTICATION_REQUIRED' | 'RESOURCE_UNAVAILABLE' | 'AUTHORIZATION_REVOKED' | 'CONVERSATION_UNAVAILABLE' | 'EXECUTION_FAILED' | 'MODEL_SELECTION_INVALID' | 'CONNECTION_AUTHORIZATION_REQUIRED' | 'ACTION_UNAVAILABLE' | 'PROVIDER_REJECTED' | 'DELEGATED_RESULT_REJECTED' | 'ORIGINAL_RESPONSE_NOT_STARTED' | 'ORIGINAL_RESPONSE_ALREADY_FINISHED';
    message: string;
    retryable: false;
    schemaVersion: 1;
    traceId: string;
};

export type PlatformAuditProjectionV2 = {
    action: string;
    actor: {
        displayName: string;
        roles: Array<'employee' | 'system_admin'>;
        userId: string;
    } | {
        actorId: string;
        kind: 'application';
    } | {
        actorId: 'unknown';
        kind: 'unknown';
    } | {
        actorId: string;
        kind: 'system';
    };
    auditId: string;
    occurredAt: string;
    result: 'succeeded' | 'failed';
    schemaVersion: 2;
    subjectId: string;
    subjectType: 'agent_application' | 'agent' | 'configuration' | 'grant' | 'unknown';
    summary: string;
    traceId: string;
};

export type RuntimeConnectionAssociationV1 = {
    callRef: string;
    serviceRef: string;
    verification: 'verified';
} | {
    callRef?: string;
    reason: 'receipt_missing' | 'record_unavailable' | 'authorization_unavailable' | 'binding_mismatch' | 'response_unconfirmed';
    serviceRef: string;
    verification: 'unverified';
};

export type RuntimeOperationFactV2 = {
    attemptRef: string;
    durationMs?: number;
    failureCode?: RuntimeOperationFailureV2;
    finishedAt?: string;
    kind: 'model';
    model: {
        configVersion: string;
        modelId: string;
        modelOptionId: string;
        reasoningLevel?: string;
    };
    operationRef: string;
    parentOperationRef?: string;
    phase: 'intent' | 'started' | 'completed' | 'failed' | 'unknown';
    startedAt?: string;
    usage?: {
        cachedInputTokens?: number;
        inputTokens?: number;
        outputTokens?: number;
    };
} | {
    attemptRef: string;
    connection?: RuntimeConnectionAssociationV1;
    durationMs?: number;
    failureCode?: RuntimeOperationFailureV2;
    finishedAt?: string;
    kind: 'tool';
    operationRef: string;
    parentOperationRef?: string;
    phase: 'intent' | 'started' | 'completed' | 'failed' | 'unknown';
    resultRef?: string;
    startedAt?: string;
    toolId: string;
};

export type RuntimeOperationFailureV2 = 'authorization_denied' | 'authorization_unavailable' | 'dependency_unavailable' | 'request_rejected' | 'response_incomplete' | 'operation_failed' | 'persistence_unavailable' | 'interrupted' | 'recovery_unconfirmed';

export type SkillHubDirectoryPageV1 = {
    items: Array<SkillHubVersionMetadataV1>;
    nextCursor: string | null;
};

export type SkillHubVersionMetadataV1 = {
    manifestDigest: string;
    name: string;
    packageDigest: string;
    provider: 'system' | 'my_library' | 'market' | 'clawhub' | 'skillhub' | 'npx' | 'github';
    schemaVersion: 1;
    signatureDigest: string;
    skillId: string;
    skillVersionId: string;
    state: 'published';
    version: string;
    visibility: 'PRIVATE' | 'MEMBER' | 'ORGANIZATION' | 'MARKET';
};

export type SseEventIdV1 = string;

export type TimelineReloadSignalV1 = {
    kind: 'control';
    reason: 'unknown_event_id' | 'cross_conversation_cursor' | 'cross_conversation_event_id' | 'cursor_expired';
    resumeCursor: string;
    schemaVersion: 1;
    type: 'timeline.reload';
};

export type AgentApiCreationRequestV1Writable = {
    availability: Array<{
        kind: 'user';
        userId: string;
    } | {
        kind: 'organization';
        organizationId: string;
    }>;
    coOwnerIds: Array<string>;
    description: string;
    environment: Array<{
        name: string;
        value: string;
    }>;
    name: string;
    schemaVersion: 2;
    secrets: Array<{
        name: string;
        value: string;
    }>;
    source: {
        identityResponsibility: 'self-managed' | 'platform-managed';
        imageReference: string;
        interactionMode: 'self-managed';
        kind: 'custom';
    } | {
        imageReference: string;
        interactionMode: 'platform-adapter';
        kind: 'custom';
    };
} | {
    availability: Array<{
        kind: 'user';
        userId: string;
    } | {
        kind: 'organization';
        organizationId: string;
    }>;
    coOwnerIds: Array<string>;
    defaultRelayKey: string;
    description: string;
    environment: Array<{
        name: string;
        value: string;
    }>;
    modelConfiguration: {
        defaultOptionId: string;
        defaultReasoningLevel: string;
        options: Array<{
            endpointId: string;
            modelId: string;
            optionId: string;
            reasoningLevels: Array<string>;
        }>;
    };
    name: string;
    schemaVersion: 3;
    secrets: Array<{
        name: string;
        value: string;
    }>;
    source: {
        kind: 'standard';
        templateId: string;
    };
};

export type AgentApplicationCreateRequestV2Writable = {
    availability: Array<{
        kind: 'user';
        userId: string;
    } | {
        kind: 'organization';
        organizationId: string;
    }>;
    coOwnerIds: Array<string>;
    description: string;
    environment: Array<{
        name: string;
        value: string;
    }>;
    modelConfiguration?: {
        defaultOptionId: string;
        defaultReasoningLevel: string;
        options: Array<{
            credentialValue?: string;
            endpointId: string;
            modelId: string;
            optionId: string;
            reasoningLevels: Array<string>;
        }>;
    };
    name: string;
    schemaVersion: 2;
    secrets: Array<{
        name: string;
        value: string;
    }>;
    source: {
        kind: 'standard';
        templateId: string;
    } | {
        identityResponsibility: 'self-managed' | 'platform-managed';
        imageReference: string;
        interactionMode: 'self-managed';
        kind: 'custom';
    } | {
        imageReference: string;
        interactionMode: 'platform-adapter';
        kind: 'custom';
    };
};

export type AgentApplicationUpdateRequestV2Writable = {
    availability: Array<{
        kind: 'user';
        userId: string;
    } | {
        kind: 'organization';
        organizationId: string;
    }>;
    coOwnerIds: Array<string>;
    description: string;
    environment: Array<{
        name: string;
        value: string;
    }>;
    modelConfiguration?: {
        defaultOptionId: string;
        defaultReasoningLevel: string;
        options: Array<{
            credentialValue?: string;
            endpointId: string;
            modelId: string;
            optionId: string;
            reasoningLevels: Array<string>;
        }>;
    };
    name: string;
    schemaVersion: 2;
    secrets?: Array<{
        name: string;
        value: string;
    }>;
    source: {
        kind: 'standard';
        templateId: string;
    } | {
        identityResponsibility: 'self-managed' | 'platform-managed';
        imageReference: string;
        interactionMode: 'self-managed';
        kind: 'custom';
    } | {
        imageReference: string;
        interactionMode: 'platform-adapter';
        kind: 'custom';
    };
};

export type AgentConfigurationUpdateRequestV2Writable = {
    availability?: Array<{
        kind: 'user';
        userId: string;
    } | {
        kind: 'organization';
        organizationId: string;
    }>;
    channels?: Array<{
        bindingReference: string;
        enabled: true;
        kind: 'wecom_bot' | 'wecom_app';
    } | {
        enabled: false;
        kind: 'wecom_bot' | 'wecom_app';
    }>;
    coOwnerIds?: Array<string>;
    environment?: Array<{
        name: string;
        value: string;
    }>;
    modelConfiguration?: {
        defaultOptionId: string;
        defaultReasoningLevel: string;
        options: Array<{
            credentialValue?: string;
            endpointId: string;
            modelId: string;
            optionId: string;
            reasoningLevels: Array<string>;
        }>;
    };
    schemaVersion: 2;
    secrets?: Array<{
        name: string;
        value: string;
    }>;
};

export type BeginPlatformConnectionInstallationV1Data = {
    body: {
        executionId: string;
        schemaVersion: 1;
    };
    headers: {
        Origin: string;
        'X-Platform-CSRF': '1';
        'Sec-Fetch-Site'?: 'same-origin';
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/connection-installations';
};

export type BeginPlatformConnectionInstallationV1Responses = {
    /**
     * Platform installation confirmation fact; no credential or Connection Grant
     */
    202: {
        authorizationId: string;
        authorizationUrl?: string;
        expiresAt: number;
        schemaVersion: 1;
        status: 'awaiting_confirmation' | 'confirmed' | 'revoked' | 'expired' | 'unknown';
    };
};

export type BeginPlatformConnectionInstallationV1Response = BeginPlatformConnectionInstallationV1Responses[keyof BeginPlatformConnectionInstallationV1Responses];

export type ReadPlatformConnectionInstallationV1Data = {
    body?: never;
    headers: {
        Origin: string;
        'X-Platform-CSRF': '1';
        'Sec-Fetch-Site'?: 'same-origin';
    };
    path: {
        authorizationId: string;
    };
    query?: never;
    url: '/api/connection-installations/{authorizationId}';
};

export type ReadPlatformConnectionInstallationV1Responses = {
    /**
     * Platform installation confirmation fact; no credential or Connection Grant
     */
    200: {
        authorizationId: string;
        authorizationUrl?: string;
        expiresAt: number;
        schemaVersion: 1;
        status: 'awaiting_confirmation' | 'confirmed' | 'revoked' | 'expired' | 'unknown';
    };
};

export type ReadPlatformConnectionInstallationV1Response = ReadPlatformConnectionInstallationV1Responses[keyof ReadPlatformConnectionInstallationV1Responses];

export type ConfirmPlatformConnectionInstallationV1Data = {
    body: {
        schemaVersion: 1;
    };
    headers: {
        Origin: string;
        'X-Platform-CSRF': '1';
        'Sec-Fetch-Site'?: 'same-origin';
        'Idempotency-Key': string;
    };
    path: {
        authorizationId: string;
    };
    query?: never;
    url: '/api/connection-installations/{authorizationId}/confirm';
};

export type ConfirmPlatformConnectionInstallationV1Responses = {
    /**
     * Platform installation confirmation fact; no credential or Connection Grant
     */
    202: {
        authorizationId: string;
        authorizationUrl?: string;
        expiresAt: number;
        schemaVersion: 1;
        status: 'awaiting_confirmation' | 'confirmed' | 'revoked' | 'expired' | 'unknown';
    };
};

export type ConfirmPlatformConnectionInstallationV1Response = ConfirmPlatformConnectionInstallationV1Responses[keyof ConfirmPlatformConnectionInstallationV1Responses];

export type ListPendingAgentApplicationsV2Data = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/api/v2/admin/agent-applications';
};

export type ListPendingAgentApplicationsV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type ListPendingAgentApplicationsV2Error = ListPendingAgentApplicationsV2Errors[keyof ListPendingAgentApplicationsV2Errors];

export type ListPendingAgentApplicationsV2Responses = {
    /**
     * Pending applications
     */
    200: {
        items: Array<AgentApplicationProjectionV2>;
        nextCursor: string | null;
    };
};

export type ListPendingAgentApplicationsV2Response = ListPendingAgentApplicationsV2Responses[keyof ListPendingAgentApplicationsV2Responses];

export type DecideAgentApplicationV2Data = {
    body: ApprovalDecisionRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/api/v2/admin/agent-applications/{applicationId}/decision';
};

export type DecideAgentApplicationV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type DecideAgentApplicationV2Error = DecideAgentApplicationV2Errors[keyof DecideAgentApplicationV2Errors];

export type DecideAgentApplicationV2Responses = {
    /**
     * Application decision
     */
    200: AgentApplicationProjectionV2;
};

export type DecideAgentApplicationV2Response = DecideAgentApplicationV2Responses[keyof DecideAgentApplicationV2Responses];

export type ListAdminAgentsV2Data = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/api/v2/admin/agents';
};

export type ListAdminAgentsV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type ListAdminAgentsV2Error = ListAdminAgentsV2Errors[keyof ListAdminAgentsV2Errors];

export type ListAdminAgentsV2Responses = {
    /**
     * Administrator agents
     */
    200: {
        items: Array<AgentProjectionV2>;
        nextCursor: string | null;
    };
};

export type ListAdminAgentsV2Response = ListAdminAgentsV2Responses[keyof ListAdminAgentsV2Responses];

export type ListPlatformAuditV2Data = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/api/v2/admin/audit';
};

export type ListPlatformAuditV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type ListPlatformAuditV2Error = ListPlatformAuditV2Errors[keyof ListPlatformAuditV2Errors];

export type ListPlatformAuditV2Responses = {
    /**
     * Platform audit
     */
    200: {
        items: Array<PlatformAuditProjectionV2>;
        nextCursor: string | null;
    };
};

export type ListPlatformAuditV2Response = ListPlatformAuditV2Responses[keyof ListPlatformAuditV2Responses];

export type ListAgentApplicationsV2Data = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/api/v2/agent-applications';
};

export type ListAgentApplicationsV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type ListAgentApplicationsV2Error = ListAgentApplicationsV2Errors[keyof ListAgentApplicationsV2Errors];

export type ListAgentApplicationsV2Responses = {
    /**
     * Current user's applications
     */
    200: {
        items: Array<AgentApplicationProjectionV2>;
        nextCursor: string | null;
    };
};

export type ListAgentApplicationsV2Response = ListAgentApplicationsV2Responses[keyof ListAgentApplicationsV2Responses];

export type CreateAgentApplicationV2Data = {
    body: AgentApplicationCreateRequestV2Writable;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/v2/agent-applications';
};

export type CreateAgentApplicationV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type CreateAgentApplicationV2Error = CreateAgentApplicationV2Errors[keyof CreateAgentApplicationV2Errors];

export type CreateAgentApplicationV2Responses = {
    /**
     * Application submitted
     */
    201: AgentApplicationProjectionV2;
};

export type CreateAgentApplicationV2Response = CreateAgentApplicationV2Responses[keyof CreateAgentApplicationV2Responses];

export type GetAgentApplicationV2Data = {
    body?: never;
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/api/v2/agent-applications/{applicationId}';
};

export type GetAgentApplicationV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type GetAgentApplicationV2Error = GetAgentApplicationV2Errors[keyof GetAgentApplicationV2Errors];

export type GetAgentApplicationV2Responses = {
    /**
     * Application detail
     */
    200: AgentApplicationProjectionV2;
};

export type GetAgentApplicationV2Response = GetAgentApplicationV2Responses[keyof GetAgentApplicationV2Responses];

export type UpdateAgentApplicationV2Data = {
    body: AgentApplicationUpdateRequestV2Writable;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/api/v2/agent-applications/{applicationId}';
};

export type UpdateAgentApplicationV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type UpdateAgentApplicationV2Error = UpdateAgentApplicationV2Errors[keyof UpdateAgentApplicationV2Errors];

export type UpdateAgentApplicationV2Responses = {
    /**
     * Application updated
     */
    200: AgentApplicationProjectionV2;
};

export type UpdateAgentApplicationV2Response = UpdateAgentApplicationV2Responses[keyof UpdateAgentApplicationV2Responses];

export type WithdrawAgentApplicationV2Data = {
    body?: never;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/api/v2/agent-applications/{applicationId}/withdraw';
};

export type WithdrawAgentApplicationV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type WithdrawAgentApplicationV2Error = WithdrawAgentApplicationV2Errors[keyof WithdrawAgentApplicationV2Errors];

export type WithdrawAgentApplicationV2Responses = {
    /**
     * Application withdrawn
     */
    200: AgentApplicationProjectionV2;
};

export type WithdrawAgentApplicationV2Response = WithdrawAgentApplicationV2Responses[keyof WithdrawAgentApplicationV2Responses];

export type ListAgentsV2Data = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
        scope?: 'owner';
    };
    url: '/api/v2/agents';
};

export type ListAgentsV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type ListAgentsV2Error = ListAgentsV2Errors[keyof ListAgentsV2Errors];

export type ListAgentsV2Responses = {
    /**
     * Visible agents
     */
    200: {
        items: Array<AgentProjectionV2>;
        nextCursor: string | null;
    };
};

export type ListAgentsV2Response = ListAgentsV2Responses[keyof ListAgentsV2Responses];

export type CreateAgentApiV1Data = {
    body: AgentApiCreationRequestV1Writable;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/v2/agents';
};

export type CreateAgentApiV1Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type CreateAgentApiV1Error = CreateAgentApiV1Errors[keyof CreateAgentApiV1Errors];

export type CreateAgentApiV1Responses = {
    /**
     * Original Agent API creation replayed
     */
    200: AgentApiCreationResponseV1;
    /**
     * Agent API creation accepted
     */
    201: AgentApiCreationResponseV1;
};

export type CreateAgentApiV1Response = CreateAgentApiV1Responses[keyof CreateAgentApiV1Responses];

export type GetAgentV2Data = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/api/v2/agents/{agentId}';
};

export type GetAgentV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type GetAgentV2Error = GetAgentV2Errors[keyof GetAgentV2Errors];

export type GetAgentV2Responses = {
    /**
     * Agent detail
     */
    200: AgentProjectionV2;
};

export type GetAgentV2Response = GetAgentV2Responses[keyof GetAgentV2Responses];

export type RevokeAgentUserApiUseV1Data = {
    body: AgentUserUseRevokeRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        agentId: string;
        userId: string;
    };
    query?: never;
    url: '/api/v2/agents/{agentId}/api-use-grants/{userId}';
};

export type RevokeAgentUserApiUseV1Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type RevokeAgentUserApiUseV1Error = RevokeAgentUserApiUseV1Errors[keyof RevokeAgentUserApiUseV1Errors];

export type RevokeAgentUserApiUseV1Responses = {
    /**
     * Explicit user API use revocation
     */
    200: AgentUserUseRevokeResponseV1;
};

export type RevokeAgentUserApiUseV1Response = RevokeAgentUserApiUseV1Responses[keyof RevokeAgentUserApiUseV1Responses];

export type RevokeAgentApplicationManagerV1Data = {
    body: AgentApplicationManagerRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        agentId: string;
        applicationId: string;
    };
    query?: never;
    url: '/api/v2/agents/{agentId}/application-managers/{applicationId}';
};

export type RevokeAgentApplicationManagerV1Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type RevokeAgentApplicationManagerV1Error = RevokeAgentApplicationManagerV1Errors[keyof RevokeAgentApplicationManagerV1Errors];

export type RevokeAgentApplicationManagerV1Responses = {
    /**
     * Explicit application manage revocation
     */
    200: AgentApplicationManagerResponseV1;
};

export type RevokeAgentApplicationManagerV1Response = RevokeAgentApplicationManagerV1Responses[keyof RevokeAgentApplicationManagerV1Responses];

export type GrantAgentApplicationManagerV1Data = {
    body: AgentApplicationManagerRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        agentId: string;
        applicationId: string;
    };
    query?: never;
    url: '/api/v2/agents/{agentId}/application-managers/{applicationId}';
};

export type GrantAgentApplicationManagerV1Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type GrantAgentApplicationManagerV1Error = GrantAgentApplicationManagerV1Errors[keyof GrantAgentApplicationManagerV1Errors];

export type GrantAgentApplicationManagerV1Responses = {
    /**
     * Explicit application manage grant
     */
    200: AgentApplicationManagerResponseV1;
};

export type GrantAgentApplicationManagerV1Response = GrantAgentApplicationManagerV1Responses[keyof GrantAgentApplicationManagerV1Responses];

export type RevokeAgentApplicationUseV1Data = {
    body: AgentApplicationManagerRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        agentId: string;
        applicationId: string;
    };
    query?: never;
    url: '/api/v2/agents/{agentId}/application-use-grants/{applicationId}';
};

export type RevokeAgentApplicationUseV1Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type RevokeAgentApplicationUseV1Error = RevokeAgentApplicationUseV1Errors[keyof RevokeAgentApplicationUseV1Errors];

export type RevokeAgentApplicationUseV1Responses = {
    /**
     * Explicit application use revocation
     */
    200: AgentApplicationManagerResponseV1;
};

export type RevokeAgentApplicationUseV1Response = RevokeAgentApplicationUseV1Responses[keyof RevokeAgentApplicationUseV1Responses];

export type GrantAgentApplicationUseV1Data = {
    body: AgentApplicationManagerRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        agentId: string;
        applicationId: string;
    };
    query?: never;
    url: '/api/v2/agents/{agentId}/application-use-grants/{applicationId}';
};

export type GrantAgentApplicationUseV1Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type GrantAgentApplicationUseV1Error = GrantAgentApplicationUseV1Errors[keyof GrantAgentApplicationUseV1Errors];

export type GrantAgentApplicationUseV1Responses = {
    /**
     * Explicit application use grant
     */
    200: AgentApplicationManagerResponseV1;
};

export type GrantAgentApplicationUseV1Response = GrantAgentApplicationUseV1Responses[keyof GrantAgentApplicationUseV1Responses];

export type CommandAgentApiLifecycleV1Data = {
    body: AgentApiLifecycleRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        agentId: string;
    };
    query?: never;
    url: '/api/v2/agents/{agentId}/commands';
};

export type CommandAgentApiLifecycleV1Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type CommandAgentApiLifecycleV1Error = CommandAgentApiLifecycleV1Errors[keyof CommandAgentApiLifecycleV1Errors];

export type CommandAgentApiLifecycleV1Responses = {
    /**
     * Agent lifecycle command accepted
     */
    202: AgentApiLifecycleResponseV1;
};

export type CommandAgentApiLifecycleV1Response = CommandAgentApiLifecycleV1Responses[keyof CommandAgentApiLifecycleV1Responses];

export type UpdateAgentConfigurationV2Data = {
    body: AgentConfigurationUpdateRequestV2Writable;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        agentId: string;
    };
    query?: never;
    url: '/api/v2/agents/{agentId}/configuration';
};

export type UpdateAgentConfigurationV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type UpdateAgentConfigurationV2Error = UpdateAgentConfigurationV2Errors[keyof UpdateAgentConfigurationV2Errors];

export type UpdateAgentConfigurationV2Responses = {
    /**
     * Agent configuration
     */
    200: AgentProjectionV2;
};

export type UpdateAgentConfigurationV2Response = UpdateAgentConfigurationV2Responses[keyof UpdateAgentConfigurationV2Responses];

export type CommandAgentLifecycleV2Data = {
    body: AgentLifecycleCommandRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        agentId: string;
    };
    query?: never;
    url: '/api/v2/agents/{agentId}/lifecycle';
};

export type CommandAgentLifecycleV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type CommandAgentLifecycleV2Error = CommandAgentLifecycleV2Errors[keyof CommandAgentLifecycleV2Errors];

export type CommandAgentLifecycleV2Responses = {
    /**
     * Lifecycle command accepted
     */
    202: AgentProjectionV2;
};

export type CommandAgentLifecycleV2Response = CommandAgentLifecycleV2Responses[keyof CommandAgentLifecycleV2Responses];

export type GetAgentApiStateV1Data = {
    body?: never;
    path: {
        agentId: string;
    };
    query?: never;
    url: '/api/v2/agents/{agentId}/state';
};

export type GetAgentApiStateV1Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type GetAgentApiStateV1Error = GetAgentApiStateV1Errors[keyof GetAgentApiStateV1Errors];

export type GetAgentApiStateV1Responses = {
    /**
     * Current authorized Agent lifecycle state
     */
    200: AgentApiStateResponseV1;
};

export type GetAgentApiStateV1Response = GetAgentApiStateV1Responses[keyof GetAgentApiStateV1Responses];

export type RegisterApplicationV2Data = {
    body: ApplicationRegistrationRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/v2/applications';
};

export type RegisterApplicationV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type RegisterApplicationV2Error = RegisterApplicationV2Errors[keyof RegisterApplicationV2Errors];

export type RegisterApplicationV2Responses = {
    /**
     * Original application metadata replayed
     */
    200: ApplicationRegistrationResponseV1;
    /**
     * Application committed
     */
    201: ApplicationRegistrationResponseV1;
};

export type RegisterApplicationV2Response = RegisterApplicationV2Responses[keyof RegisterApplicationV2Responses];

export type GetOwnApplicationV2Data = {
    body?: never;
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/api/v2/applications/{applicationId}';
};

export type GetOwnApplicationV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type GetOwnApplicationV2Error = GetOwnApplicationV2Errors[keyof GetOwnApplicationV2Errors];

export type GetOwnApplicationV2Responses = {
    /**
     * Own application metadata
     */
    200: ApplicationMetadataV1;
};

export type GetOwnApplicationV2Response = GetOwnApplicationV2Responses[keyof GetOwnApplicationV2Responses];

export type DisableOwnApplicationV2Data = {
    body: ApplicationDisableRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/api/v2/applications/{applicationId}';
};

export type DisableOwnApplicationV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type DisableOwnApplicationV2Error = DisableOwnApplicationV2Errors[keyof DisableOwnApplicationV2Errors];

export type DisableOwnApplicationV2Responses = {
    /**
     * Disabled application metadata
     */
    200: ApplicationMetadataV1;
};

export type DisableOwnApplicationV2Response = DisableOwnApplicationV2Responses[keyof DisableOwnApplicationV2Responses];

export type IssueOrRotateApplicationApiCredentialV2Data = {
    body: {
        expiresAt: string | null;
        operation: 'issue';
        recipient: {
            principalId: string;
            principalType: 'user' | 'application';
        };
        scopes: Array<'agent:create' | 'agent:manage' | 'agent:use' | 'agent:read'>;
    } | {
        credentialId: string;
        expiresAt: string | null;
        operation: 'rotate';
        recipient: {
            principalId: string;
            principalType: 'user' | 'application';
        };
        scopes: Array<'agent:create' | 'agent:manage' | 'agent:use' | 'agent:read'>;
    };
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/api/v2/applications/{applicationId}/credentials';
};

export type IssueOrRotateApplicationApiCredentialV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type IssueOrRotateApplicationApiCredentialV2Error = IssueOrRotateApplicationApiCredentialV2Errors[keyof IssueOrRotateApplicationApiCredentialV2Errors];

export type IssueOrRotateApplicationApiCredentialV2Responses = {
    /**
     * Original metadata and delivery status replayed
     */
    200: {
        delivery: {
            attemptId: string;
            grantRevision: string;
            recipient: {
                principalId: string;
                principalType: 'user' | 'application';
            };
            status: 'delivery_pending' | 'delivery_in_flight' | 'accepted' | 'failed' | 'unknown';
        };
        metadata: {
            applicationId: string;
            createdAt: string;
            credentialId: string;
            expiresAt: string | null;
            lastUsedAt: string | null;
            revokedAt: string | null;
            scopes: Array<'agent:create' | 'agent:manage' | 'agent:use' | 'agent:read'>;
        };
        replayed: boolean;
    };
    /**
     * Credential committed; inspect delivery status
     */
    201: {
        delivery: {
            attemptId: string;
            grantRevision: string;
            recipient: {
                principalId: string;
                principalType: 'user' | 'application';
            };
            status: 'delivery_pending' | 'delivery_in_flight' | 'accepted' | 'failed' | 'unknown';
        };
        metadata: {
            applicationId: string;
            createdAt: string;
            credentialId: string;
            expiresAt: string | null;
            lastUsedAt: string | null;
            revokedAt: string | null;
            scopes: Array<'agent:create' | 'agent:manage' | 'agent:use' | 'agent:read'>;
        };
        replayed: boolean;
    };
};

export type IssueOrRotateApplicationApiCredentialV2Response = IssueOrRotateApplicationApiCredentialV2Responses[keyof IssueOrRotateApplicationApiCredentialV2Responses];

export type GrantApplicationMaterialV2Data = {
    body: {
        expectedRevision?: string;
        principalId: string;
        principalType: 'user' | 'application';
    };
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/api/v2/applications/{applicationId}/material-grant';
};

export type GrantApplicationMaterialV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type GrantApplicationMaterialV2Error = GrantApplicationMaterialV2Errors[keyof GrantApplicationMaterialV2Errors];

export type GrantApplicationMaterialV2Responses = {
    /**
     * Material grant metadata
     */
    201: {
        metadata: {
            applicationId: string;
            authorizationRevision: string;
            createdAt: string;
            principalId: string;
            principalType: 'user' | 'application';
            revokedAt: string | null;
        };
        replayed: boolean;
    };
};

export type GrantApplicationMaterialV2Response = GrantApplicationMaterialV2Responses[keyof GrantApplicationMaterialV2Responses];

export type ReadApplicationMaterialV2Data = {
    body?: never;
    path: {
        applicationId: string;
        principalType: 'user' | 'application';
        principalId: string;
    };
    query?: never;
    url: '/api/v2/applications/{applicationId}/material-grant/{principalType}/{principalId}';
};

export type ReadApplicationMaterialV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type ReadApplicationMaterialV2Error = ReadApplicationMaterialV2Errors[keyof ReadApplicationMaterialV2Errors];

export type ReadApplicationMaterialV2Responses = {
    /**
     * Material grant metadata
     */
    200: {
        metadata: {
            applicationId: string;
            authorizationRevision: string;
            createdAt: string;
            principalId: string;
            principalType: 'user' | 'application';
            revokedAt: string | null;
        };
        replayed: boolean;
    };
};

export type ReadApplicationMaterialV2Response = ReadApplicationMaterialV2Responses[keyof ReadApplicationMaterialV2Responses];

export type RevokeApplicationMaterialV2Data = {
    body: {
        expectedRevision: string;
        status: 'revoked';
    };
    path: {
        applicationId: string;
        principalType: 'user' | 'application';
        principalId: string;
    };
    query?: never;
    url: '/api/v2/applications/{applicationId}/material-grant/{principalType}/{principalId}';
};

export type RevokeApplicationMaterialV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type RevokeApplicationMaterialV2Error = RevokeApplicationMaterialV2Errors[keyof RevokeApplicationMaterialV2Errors];

export type RevokeApplicationMaterialV2Responses = {
    /**
     * Revoked material grant metadata
     */
    200: {
        metadata: {
            applicationId: string;
            authorizationRevision: string;
            createdAt: string;
            principalId: string;
            principalType: 'user' | 'application';
            revokedAt: string | null;
        };
        replayed: boolean;
    };
};

export type RevokeApplicationMaterialV2Response = RevokeApplicationMaterialV2Responses[keyof RevokeApplicationMaterialV2Responses];

export type GetConversationV2Data = {
    body?: never;
    path: {
        conversationId: string;
    };
    query?: never;
    url: '/api/v2/conversations/{conversationId}';
};

export type GetConversationV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type GetConversationV2Error = GetConversationV2Errors[keyof GetConversationV2Errors];

export type GetConversationV2Responses = {
    /**
     * Conversation messages and complete mixed-version event history
     */
    200: ConversationDetailProjectionV2;
};

export type GetConversationV2Response = GetConversationV2Responses[keyof GetConversationV2Responses];

export type StreamConversationEventsV2Data = {
    body?: never;
    headers?: {
        'Last-Event-ID'?: SseEventIdV1;
    };
    path: {
        conversationId: string;
    };
    query?: {
        cursor?: string;
    };
    url: '/api/v2/conversations/{conversationId}/events';
};

export type StreamConversationEventsV2Errors = {
    /**
     * Invalid replay cursor
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Conversation access is unavailable
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Event stream is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type StreamConversationEventsV2Error = StreamConversationEventsV2Errors[keyof StreamConversationEventsV2Errors];

export type StreamConversationEventsV2Responses = {
    /**
     * Original V1 events, V2 operation facts and bounded V1 controls
     */
    200: ConversationSseMessageV2;
};

export type StreamConversationEventsV2Response = StreamConversationEventsV2Responses[keyof StreamConversationEventsV2Responses];

export type GetExecutionDetailV2Data = {
    body?: never;
    path: {
        conversationId: string;
        executionId: string;
    };
    query?: never;
    url: '/api/v2/conversations/{conversationId}/executions/{executionId}';
};

export type GetExecutionDetailV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type GetExecutionDetailV2Error = GetExecutionDetailV2Errors[keyof GetExecutionDetailV2Errors];

export type GetExecutionDetailV2Responses = {
    /**
     * Execution detail with original structured operation facts and event history
     */
    200: ExecutionDetailProjectionV2;
};

export type GetExecutionDetailV2Response = GetExecutionDetailV2Responses[keyof GetExecutionDetailV2Responses];

export type GetDeploymentConfigurationV2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v2/deployment/configuration';
};

export type GetDeploymentConfigurationV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type GetDeploymentConfigurationV2Error = GetDeploymentConfigurationV2Errors[keyof GetDeploymentConfigurationV2Errors];

export type GetDeploymentConfigurationV2Responses = {
    /**
     * Deployment-owned application choices
     */
    200: DeploymentConfigurationProjectionV2;
};

export type GetDeploymentConfigurationV2Response = GetDeploymentConfigurationV2Responses[keyof GetDeploymentConfigurationV2Responses];

export type ListPersonalApiCredentialsV2Data = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        cursor?: string;
    };
    url: '/api/v2/me/api-credentials';
};

export type ListPersonalApiCredentialsV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type ListPersonalApiCredentialsV2Error = ListPersonalApiCredentialsV2Errors[keyof ListPersonalApiCredentialsV2Errors];

export type ListPersonalApiCredentialsV2Responses = {
    /**
     * Personal credential metadata page
     */
    200: PersonalApiCredentialPageV1;
};

export type ListPersonalApiCredentialsV2Response = ListPersonalApiCredentialsV2Responses[keyof ListPersonalApiCredentialsV2Responses];

export type IssuePersonalApiCredentialV2Data = {
    body: PersonalApiCredentialIssueRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/v2/me/api-credentials';
};

export type IssuePersonalApiCredentialV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type IssuePersonalApiCredentialV2Error = IssuePersonalApiCredentialV2Errors[keyof IssuePersonalApiCredentialV2Errors];

export type IssuePersonalApiCredentialV2Responses = {
    /**
     * Original credential metadata; material is not replayed
     */
    200: {
        credential: null;
        metadata: PersonalApiCredentialMetadataV1;
        replayed: true;
    };
    /**
     * Credential committed with first-delivery material
     */
    201: {
        /**
         * First committed delivery only; never persisted or replayed.
         */
        credential: string;
        metadata: PersonalApiCredentialMetadataV1;
        replayed: false;
    };
};

export type IssuePersonalApiCredentialV2Response = IssuePersonalApiCredentialV2Responses[keyof IssuePersonalApiCredentialV2Responses];

export type RevokePersonalApiCredentialV2Data = {
    body?: never;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        credentialId: string;
    };
    query?: never;
    url: '/api/v2/me/api-credentials/{credentialId}';
};

export type RevokePersonalApiCredentialV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type RevokePersonalApiCredentialV2Error = RevokePersonalApiCredentialV2Errors[keyof RevokePersonalApiCredentialV2Errors];

export type RevokePersonalApiCredentialV2Responses = {
    /**
     * Current revoked credential metadata
     */
    200: PersonalApiCredentialRevokeResponseV1;
};

export type RevokePersonalApiCredentialV2Response = RevokePersonalApiCredentialV2Responses[keyof RevokePersonalApiCredentialV2Responses];

export type NarrowPersonalApiCredentialV2Data = {
    body: PersonalApiCredentialNarrowRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        credentialId: string;
    };
    query?: never;
    url: '/api/v2/me/api-credentials/{credentialId}';
};

export type NarrowPersonalApiCredentialV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type NarrowPersonalApiCredentialV2Error = NarrowPersonalApiCredentialV2Errors[keyof NarrowPersonalApiCredentialV2Errors];

export type NarrowPersonalApiCredentialV2Responses = {
    /**
     * Current restricted credential metadata
     */
    200: PersonalApiCredentialRevokeResponseV1;
};

export type NarrowPersonalApiCredentialV2Response = NarrowPersonalApiCredentialV2Responses[keyof NarrowPersonalApiCredentialV2Responses];

export type ListRecentPersonalConversationsV2Data = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/api/v2/me/conversations/recent';
};

export type ListRecentPersonalConversationsV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type ListRecentPersonalConversationsV2Error = ListRecentPersonalConversationsV2Errors[keyof ListRecentPersonalConversationsV2Errors];

export type ListRecentPersonalConversationsV2Responses = {
    /**
     * Conversation history
     */
    200: {
        items: Array<{
            agentId: string;
            conversationId: string;
            createdAt: string;
            lastConversationCursor: string | null;
            schemaVersion: 1;
            selectedModelOptionId: string | null;
            selectedReasoningLevel: string | null;
            status: 'ready' | 'active' | 'unavailable';
            title: string | null;
            updatedAt: string;
        }>;
        nextCursor: string | null;
    };
};

export type ListRecentPersonalConversationsV2Response = ListRecentPersonalConversationsV2Responses[keyof ListRecentPersonalConversationsV2Responses];

export type RevokePersonalRelayKeyV2Data = {
    body: PersonalRelayKeyRevokeRequestV1;
    path?: never;
    query?: never;
    url: '/api/v2/me/relay-key';
};

export type RevokePersonalRelayKeyV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type RevokePersonalRelayKeyV2Error = RevokePersonalRelayKeyV2Errors[keyof RevokePersonalRelayKeyV2Errors];

export type RevokePersonalRelayKeyV2Responses = {
    /**
     * Committed unset personal Key state
     */
    200: PersonalRelayKeyStateV1;
};

export type RevokePersonalRelayKeyV2Response = RevokePersonalRelayKeyV2Responses[keyof RevokePersonalRelayKeyV2Responses];

export type GetPersonalRelayKeyV2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v2/me/relay-key';
};

export type GetPersonalRelayKeyV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type GetPersonalRelayKeyV2Error = GetPersonalRelayKeyV2Errors[keyof GetPersonalRelayKeyV2Errors];

export type GetPersonalRelayKeyV2Responses = {
    /**
     * Personal Key state only
     */
    200: PersonalRelayKeyStateV1;
};

export type GetPersonalRelayKeyV2Response = GetPersonalRelayKeyV2Responses[keyof GetPersonalRelayKeyV2Responses];

export type ReplacePersonalRelayKeyV2Data = {
    body: PersonalRelayKeyReplaceRequestV1;
    path?: never;
    query?: never;
    url: '/api/v2/me/relay-key';
};

export type ReplacePersonalRelayKeyV2Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Request is not authorized
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Request conflicts with current state
     */
    409: PilotProtocolErrorV1;
    /**
     * Internal error
     */
    500: PilotInternalErrorV1;
    /**
     * Dependency is temporarily unavailable
     */
    503: PilotProtocolErrorV1;
};

export type ReplacePersonalRelayKeyV2Error = ReplacePersonalRelayKeyV2Errors[keyof ReplacePersonalRelayKeyV2Errors];

export type ReplacePersonalRelayKeyV2Responses = {
    /**
     * Committed personal Key state
     */
    200: PersonalRelayKeyStateV1;
};

export type ReplacePersonalRelayKeyV2Response = ReplacePersonalRelayKeyV2Responses[keyof ReplacePersonalRelayKeyV2Responses];

export type ListSkillHubVersionsV1Data = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/api/v2/skills';
};

export type ListSkillHubVersionsV1Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Authorization is no longer valid
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Dependency unavailable
     */
    503: PilotProtocolErrorV1;
};

export type ListSkillHubVersionsV1Error = ListSkillHubVersionsV1Errors[keyof ListSkillHubVersionsV1Errors];

export type ListSkillHubVersionsV1Responses = {
    /**
     * Visible fixed Skill versions
     */
    200: SkillHubDirectoryPageV1;
};

export type ListSkillHubVersionsV1Response = ListSkillHubVersionsV1Responses[keyof ListSkillHubVersionsV1Responses];

export type ReadSkillHubVersionV1Data = {
    body?: never;
    path: {
        skillVersionId: string;
    };
    query?: never;
    url: '/api/v2/skills/versions/{skillVersionId}';
};

export type ReadSkillHubVersionV1Errors = {
    /**
     * Invalid request
     */
    400: PilotProtocolErrorV1;
    /**
     * Authentication required
     */
    401: PilotProtocolErrorV1;
    /**
     * Authorization is no longer valid
     */
    403: PilotProtocolErrorV1;
    /**
     * Resource is unavailable
     */
    404: PilotProtocolErrorV1;
    /**
     * Dependency unavailable
     */
    503: PilotProtocolErrorV1;
};

export type ReadSkillHubVersionV1Error = ReadSkillHubVersionV1Errors[keyof ReadSkillHubVersionV1Errors];

export type ReadSkillHubVersionV1Responses = {
    /**
     * Visible fixed Skill version
     */
    200: SkillHubVersionMetadataV1;
};

export type ReadSkillHubVersionV1Response = ReadSkillHubVersionV1Responses[keyof ReadSkillHubVersionV1Responses];
