import {
	type ChildProcess,
	type ChildProcessWithoutNullStreams,
	spawn,
} from "node:child_process";
import { createHash } from "node:crypto";
import { constants } from "node:fs";
import {
	access,
	lstat,
	mkdir,
	mkdtemp,
	readFile,
	realpath,
	rm,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import {
	basename,
	delimiter,
	dirname,
	isAbsolute,
	join,
	resolve,
	sep,
} from "node:path";
import { env, platform } from "node:process";
import { TextDecoder } from "node:util";

const defaultTimeoutMs = 5_000;
const maximumTimeoutMs = 30_000;
const minimumTimeoutMs = 25;
const maximumFrameBytes = 65_536;
const maximumQueuedFrames = 256;
const realModelPattern = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const namespacedModelPattern =
	/^[A-Za-z0-9_-]+\/[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const reasoningEffortPattern = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;
const sha256Pattern = /^sha256:[a-f0-9]{64}$/;
const utf8 = new TextDecoder("utf-8", { fatal: true });
const schemaArtifactName = "codex_app_server_protocol.v2.schemas.json";
const isolatedRuntimeDirectoryPrefix = "agent-runtime-codex-home-";

export interface CodexAppServerProvenanceV2 {
	readonly protocolVersion: 2;
	readonly codexVersion: string;
	readonly upstreamTag: string;
	readonly upstreamCommit: string;
	readonly schemaSha256: string;
}

// Generated by codex app-server generate-json-schema from the pinned release.
export const CODEX_APP_SERVER_V2_PROVENANCE = Object.freeze({
	protocolVersion: 2 as const,
	codexVersion: "0.153.0",
	upstreamTag: "rust-v0.153.0",
	upstreamCommit: "41e22fee981a63b3698df7ed36bad393cda24715",
	schemaSha256:
		"sha256:d3eace08be5dca386bfd1f1e8df650058b4113f1e10870a284d775d75517576a",
});

export type CodexAppServerFrame = Readonly<Record<string, unknown>>;

export interface CodexModelAccess {
	readonly endpoint: string;
	readonly credential: string;
}

const modelCredentialEnvironmentKey = "AGENT_INFRA_CODEX_MODEL_CREDENTIAL";
// One native process per Conversation owns exactly one directory beneath this
// boundary; the pinned permission profile denies the boundary itself.
const conversationBoundaryDirectory = "conversations";
const conversationPermissionProfileId = "agent_infra_conversation";
const conversationKeyPattern = /^[a-f0-9]{64}$/;
const loopbackProxyExclusions = "127.0.0.1,::1,localhost";
// Every Landlock filesystem right the pinned ABI V5 admission requires.
const landlockDataRights = [
	"execute",
	"write-file",
	"read-file",
	"read-dir",
	"remove-dir",
	"remove-file",
	"make-char",
	"make-dir",
	"make-reg",
	"make-sock",
	"make-fifo",
	"make-block",
	"make-sym",
	"refer",
	"truncate",
	"ioctl-dev",
].join(",");
const landlockProgramRights = "execute,read-file,read-dir";
const landlockMetadataRights = "read-file,read-dir";

/**
 * Stable native storage key for one Conversation generation. Derived from
 * server-resolved identity only, so a wire field can never select or traverse
 * into another Conversation's native directory.
 */
export function codexConversationKey(binding: {
	readonly agentId: string;
	readonly conversationId: string;
	readonly sessionGeneration: number;
}) {
	return createHash("sha256")
		.update(
			JSON.stringify([
				binding.agentId,
				binding.conversationId,
				binding.sessionGeneration,
			]),
		)
		.digest("hex");
}

export interface CodexAppServerBridgeOptions {
	readonly launchPath?: string;
	// Deployment-owned storage on the current Agent PVC; never a wire input.
	readonly dataDirectory: string;
	// Server-derived Conversation storage key from codexConversationKey.
	readonly conversationKey: string;
	readonly model: string;
	readonly reasoningEffort: string;
	readonly modelAccess?: CodexModelAccess;
	readonly provenance: CodexAppServerProvenanceV2;
	readonly startupTimeoutMs?: number;
	readonly shutdownTimeoutMs?: number;
}

type CodexAppServerBridgeErrorCode =
	| "CODEX_APP_SERVER_CONFIGURATION_INVALID"
	| "CODEX_APP_SERVER_PROVENANCE_MISMATCH"
	| "CODEX_APP_SERVER_UNAVAILABLE"
	| "CODEX_APP_SERVER_SANDBOX_UNAVAILABLE"
	| "CODEX_APP_SERVER_TIMEOUT"
	| "CODEX_APP_SERVER_EXITED"
	| "CODEX_APP_SERVER_FRAME_INVALID"
	| "CODEX_APP_SERVER_CLOSED";

export class CodexAppServerBridgeError extends Error {
	readonly retryable: boolean;

	constructor(
		readonly code: CodexAppServerBridgeErrorCode,
		message: string,
		retryable = false,
	) {
		super(message);
		this.name = "CodexAppServerBridgeError";
		this.retryable = retryable;
	}
}

interface ValidatedOptions {
	readonly launchPath?: string;
	dataDirectory: string;
	conversationKey: string;
	model: string;
	reasoningEffort: string;
	modelAccess?: CodexModelAccess;
	startupTimeoutMs: number;
	shutdownTimeoutMs: number;
}

interface IsolatedLaunchPolicy {
	directory: string;
	environment: NodeJS.ProcessEnv;
}

interface QueueWaiter {
	resolve: (value: IteratorResult<CodexAppServerFrame>) => void;
	reject: (reason: CodexAppServerBridgeError) => void;
}

class FrameQueue {
	private readonly values: CodexAppServerFrame[] = [];
	private readonly waiters: QueueWaiter[] = [];
	private failure?: CodexAppServerBridgeError;
	private finished = false;

	push(value: CodexAppServerFrame) {
		if (this.finished || this.failure) return false;
		const waiter = this.waiters.shift();
		if (waiter) {
			waiter.resolve({ done: false, value });
			return true;
		}
		if (this.values.length >= maximumQueuedFrames) return false;
		this.values.push(value);
		return true;
	}

	fail(error: CodexAppServerBridgeError) {
		if (this.finished || this.failure) return;
		this.failure = error;
		for (const waiter of this.waiters.splice(0)) waiter.reject(error);
	}

	finish() {
		if (this.finished || this.failure) return;
		this.finished = true;
		for (const waiter of this.waiters.splice(0)) {
			waiter.resolve({ done: true, value: undefined });
		}
	}

	next(): Promise<IteratorResult<CodexAppServerFrame>> {
		if (this.failure) return Promise.reject(this.failure);
		const value = this.values.shift();
		if (value) return Promise.resolve({ done: false, value });
		if (this.finished) return Promise.resolve({ done: true, value: undefined });
		return new Promise((resolve, reject) =>
			this.waiters.push({ resolve, reject }),
		);
	}
}

function configurationInvalid(): never {
	throw new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_CONFIGURATION_INVALID",
		"Codex app-server configuration is invalid",
	);
}

function provenanceMismatch(): never {
	throw new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_PROVENANCE_MISMATCH",
		"Codex app-server provenance does not match the pinned release",
	);
}

function unavailable() {
	return new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_UNAVAILABLE",
		"Codex app-server is unavailable",
		true,
	);
}

function timedOut() {
	return new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_TIMEOUT",
		"Codex app-server did not respond before the configured timeout",
		true,
	);
}

function exited() {
	return new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_EXITED",
		"Codex app-server exited unexpectedly",
		true,
	);
}

function invalidFrame() {
	return new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_FRAME_INVALID",
		"Codex app-server emitted an invalid frame",
	);
}

function closed() {
	return new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_CLOSED",
		"Codex app-server bridge is closed",
	);
}

function isPlainRecord(value: unknown): value is Record<string, unknown> {
	return (
		typeof value === "object" &&
		value !== null &&
		!Array.isArray(value) &&
		Object.getPrototypeOf(value) === Object.prototype
	);
}

function exactKeys(value: Record<string, unknown>, keys: readonly string[]) {
	return (
		Object.keys(value).length === keys.length &&
		Object.keys(value).every((key) => keys.includes(key))
	);
}

function hasPinnedProvenance(
	value: unknown,
): value is CodexAppServerProvenanceV2 {
	if (
		!isPlainRecord(value) ||
		!exactKeys(value, [
			"protocolVersion",
			"codexVersion",
			"upstreamTag",
			"upstreamCommit",
			"schemaSha256",
		]) ||
		value.protocolVersion !== 2 ||
		typeof value.codexVersion !== "string" ||
		typeof value.upstreamTag !== "string" ||
		typeof value.upstreamCommit !== "string" ||
		typeof value.schemaSha256 !== "string" ||
		!sha256Pattern.test(value.schemaSha256)
	) {
		return false;
	}
	return (
		value.codexVersion === CODEX_APP_SERVER_V2_PROVENANCE.codexVersion &&
		value.upstreamTag === CODEX_APP_SERVER_V2_PROVENANCE.upstreamTag &&
		value.upstreamCommit === CODEX_APP_SERVER_V2_PROVENANCE.upstreamCommit &&
		value.schemaSha256 === CODEX_APP_SERVER_V2_PROVENANCE.schemaSha256
	);
}

function parseTimeout(value: unknown, fallback: number) {
	if (value === undefined) return fallback;
	if (
		typeof value !== "number" ||
		!Number.isSafeInteger(value) ||
		value < minimumTimeoutMs ||
		value > maximumTimeoutMs
	) {
		configurationInvalid();
	}
	return value;
}

function validateOptions(input: unknown): ValidatedOptions {
	if (!isPlainRecord(input)) configurationInvalid();
	const allowedKeys = [
		"launchPath",
		"dataDirectory",
		"conversationKey",
		"model",
		"reasoningEffort",
		"modelAccess",
		"provenance",
		"startupTimeoutMs",
		"shutdownTimeoutMs",
	];
	if (!Object.keys(input).every((key) => allowedKeys.includes(key))) {
		configurationInvalid();
	}
	if (
		typeof input.dataDirectory !== "string" ||
		!isAbsolute(input.dataDirectory) ||
		dirname(input.dataDirectory) === input.dataDirectory ||
		resolve(input.dataDirectory) !== input.dataDirectory ||
		[...input.dataDirectory].some(
			(character) => character.charCodeAt(0) < 32,
		) ||
		typeof input.conversationKey !== "string" ||
		!conversationKeyPattern.test(input.conversationKey) ||
		typeof input.model !== "string" ||
		(!realModelPattern.test(input.model) &&
			!namespacedModelPattern.test(input.model)) ||
		typeof input.reasoningEffort !== "string" ||
		!reasoningEffortPattern.test(input.reasoningEffort)
	) {
		configurationInvalid();
	}
	if (
		input.launchPath !== undefined &&
		(typeof input.launchPath !== "string" ||
			!input.launchPath ||
			[...input.launchPath].some(
				(character) =>
					character.charCodeAt(0) < 32 || character.charCodeAt(0) === 127,
			) ||
			input.launchPath
				.split(delimiter)
				.some((entry) => !entry || !isAbsolute(entry)))
	)
		configurationInvalid();
	if (!hasPinnedProvenance(input.provenance)) provenanceMismatch();
	const modelAccess = validateModelAccess(input.modelAccess);
	if (modelAccess && !namespacedModelPattern.test(input.model)) {
		configurationInvalid();
	}
	return {
		...(input.launchPath !== undefined ? { launchPath: input.launchPath } : {}),
		dataDirectory: input.dataDirectory,
		conversationKey: input.conversationKey,
		model: input.model,
		reasoningEffort: input.reasoningEffort,
		...(modelAccess ? { modelAccess } : {}),
		startupTimeoutMs: parseTimeout(input.startupTimeoutMs, defaultTimeoutMs),
		shutdownTimeoutMs: parseTimeout(input.shutdownTimeoutMs, defaultTimeoutMs),
	};
}

export function validateModelAccess(
	input: unknown,
): CodexModelAccess | undefined {
	if (input === undefined) return undefined;
	if (
		!isPlainRecord(input) ||
		!exactKeys(input, ["endpoint", "credential"]) ||
		typeof input.endpoint !== "string" ||
		input.endpoint.length > 2048 ||
		/[\s\\?#]/.test(input.endpoint) ||
		typeof input.credential !== "string" ||
		!/^[\x21-\x7e]{16,8192}$/.test(input.credential)
	) {
		configurationInvalid();
	}
	try {
		const endpoint = new URL(input.endpoint);
		// Match the literal authority, not URL-normalized numeric host aliases.
		const literalLoopback =
			/^http:\/\/(?:127\.0\.0\.1|\[::1\])(?::[0-9]+)?(?:\/|$)/.test(
				input.endpoint,
			);
		if (
			(endpoint.protocol !== "https:" && !literalLoopback) ||
			endpoint.username ||
			endpoint.password ||
			endpoint.search ||
			endpoint.hash
		) {
			configurationInvalid();
		}
	} catch {
		configurationInvalid();
	}
	return { endpoint: input.endpoint, credential: input.credential };
}

function modelAccessArguments(access: CodexModelAccess | undefined) {
	if (!access) return [];
	const settings = {
		model_provider: "agent_infra",
		"model_providers.agent_infra.name": "Agent Infra Active Model",
		"model_providers.agent_infra.base_url": access.endpoint,
		"model_providers.agent_infra.env_key": modelCredentialEnvironmentKey,
		"model_providers.agent_infra.wire_api": "responses",
		"model_providers.agent_infra.requires_openai_auth": false,
		"model_providers.agent_infra.supports_websockets": false,
		"model_providers.agent_infra.request_max_retries": 0,
		"model_providers.agent_infra.stream_max_retries": 0,
	};
	return Object.entries(settings).flatMap(([key, value]) => [
		"--config",
		`${key}=${JSON.stringify(value)}`,
	]);
}

function kill(
	process: Pick<ChildProcess, "kill">,
	signal: "SIGTERM" | "SIGKILL" = "SIGTERM",
) {
	try {
		process.kill(signal);
	} catch {
		// The process already exited.
	}
}

async function waitForResult<T>(promise: Promise<T>, timeoutMs: number) {
	let timer: ReturnType<typeof setTimeout> | undefined;
	try {
		return await Promise.race([
			promise,
			new Promise<undefined>((resolve) => {
				timer = setTimeout(() => resolve(undefined), timeoutMs);
			}),
		]);
	} finally {
		if (timer) clearTimeout(timer);
	}
}

async function reapChild(
	process: Pick<ChildProcess, "kill">,
	closed: Promise<true>,
	timeoutMs: number,
) {
	kill(process);
	if (await waitForResult(closed, timeoutMs)) return;
	kill(process, "SIGKILL");
	await waitForResult(closed, timeoutMs);
}

async function resolveExecutable(path: string | undefined, name: string) {
	if (!path) throw unavailable();
	for (const directory of path.split(delimiter)) {
		if (!directory) continue;
		const candidate = join(directory, name);
		try {
			await access(candidate, constants.X_OK);
			return await realpath(candidate);
		} catch {
			// Continue searching only PATH entries.
		}
	}
	throw unavailable();
}

async function createIsolatedLaunchPolicy(
	path: string | undefined,
): Promise<IsolatedLaunchPolicy> {
	if (!path) throw unavailable();
	try {
		const directory = await mkdtemp(
			join(tmpdir(), isolatedRuntimeDirectoryPrefix),
		);
		const environment: NodeJS.ProcessEnv = {
			CODEX_HOME: directory,
			HOME: directory,
			PATH: path,
		};
		if (process.platform === "darwin") {
			environment.__CF_USER_TEXT_ENCODING =
				process.env.__CF_USER_TEXT_ENCODING ?? "";
		}
		return {
			directory,
			environment,
		};
	} catch {
		throw unavailable();
	}
}

async function removeIsolatedDirectory(directory: string) {
	try {
		await rm(directory, { recursive: true, force: true });
	} catch {
		// Only the ephemeral HOME/probe/scratch directory is eligible for cleanup.
	}
}

interface ConversationLaunchPolicy extends IsolatedLaunchPolicy {
	// Native filesystem boundary the enforced policy excludes.
	boundary: string;
	root: string;
	home: string;
}

async function ensureOwnedDirectory(directory: string, create: boolean) {
	if (create) {
		await mkdir(directory, { mode: 0o700 }).catch(
			(error: NodeJS.ErrnoException) => {
				if (error.code !== "EEXIST") throw error;
			},
		);
	}
	const metadata = await lstat(directory);
	if (
		!metadata.isDirectory() ||
		(process.getuid &&
			(metadata.uid !== process.getuid() || (metadata.mode & 0o077) !== 0))
	)
		configurationInvalid();
}

async function persistentLaunchPolicy(
	dataDirectory: string,
	conversationKey: string,
	isolated: IsolatedLaunchPolicy,
): Promise<ConversationLaunchPolicy> {
	try {
		// Resolve the deployment parent (for example a mounted PVC), never follow a
		// symlink at the data root or any native data directory.
		const parent = await realpath(dirname(dataDirectory));
		const dataRoot = join(parent, basename(dataDirectory));
		for (const personal of [
			process.env.HOME,
			process.env.CODEX_HOME,
			process.cwd(),
		]) {
			if (!personal) continue;
			const canonical = await realpath(personal).catch(() => resolve(personal));
			const personalPrefix = canonical.endsWith(sep)
				? canonical
				: `${canonical}${sep}`;
			if (
				canonical === dataRoot ||
				canonical.startsWith(`${dataRoot}${sep}`) ||
				dataRoot.startsWith(personalPrefix)
			)
				configurationInvalid();
		}
		// One directory per Conversation generation beneath a shared boundary. The
		// key is server-derived, so siblings can never be named by a wire field.
		const boundary = join(dataRoot, conversationBoundaryDirectory);
		const root = join(boundary, conversationKey);
		const home = join(root, "home");
		const workspace = join(root, "workspace");
		await ensureOwnedDirectory(dataRoot, true);
		await ensureOwnedDirectory(boundary, true);
		// A Conversation that already owns storage never has a lost directory
		// recreated; its native operations and replay fail closed instead.
		const existing = await lstat(root).catch((error: NodeJS.ErrnoException) => {
			if (error.code === "ENOENT") return undefined;
			throw error;
		});
		for (const directory of [root, home, workspace]) {
			await ensureOwnedDirectory(directory, !existing);
		}
		// Durable native state is not a source of credentials or configuration.
		for (const file of [
			join(home, "config.toml"),
			join(home, "managed_config.toml"),
			join(home, "auth.json"),
			join(workspace, ".codex"),
		]) {
			const found = await lstat(file).catch((error: NodeJS.ErrnoException) => {
				if (error.code === "ENOENT") return undefined;
				throw error;
			});
			if (found) configurationInvalid();
		}
		return {
			directory: workspace,
			boundary,
			root,
			home,
			environment: {
				...isolated.environment,
				CODEX_HOME: home,
				TMPDIR: isolated.directory,
			},
		};
	} catch (error) {
		if (error instanceof CodexAppServerBridgeError) throw error;
		throw unavailable();
	}
}

/**
 * Darwin cannot wrap the native process in a further restricted Seatbelt
 * profile: pinned Codex runs its own tools through `sandbox-exec`, and any
 * enforcing outer profile makes the nested `sandbox_apply` fail, which would
 * disable every tool instead of isolating Conversations. Pinned Codex therefore
 * enforces this profile itself. Denying the shared boundary keeps every other
 * Conversation's native workspace and history unreadable, while the owning
 * Conversation keeps a writable workspace and a read-only native home, so model
 * tools cannot write native configuration, skills, or history.
 */
function conversationPermissionArguments(policy: ConversationLaunchPolicy) {
	const filesystem = [
		[policy.boundary, "deny"],
		[policy.home, "read"],
		[policy.directory, "write"],
	]
		.map(
			([path, access]) => `${JSON.stringify(path)}=${JSON.stringify(access)}`,
		)
		.join(",");
	return [
		"--config",
		`permissions={${conversationPermissionProfileId}={extends=":workspace",filesystem={${filesystem}}}}`,
		"--config",
		`default_permissions=${JSON.stringify(conversationPermissionProfileId)}`,
	];
}

async function existingDirectory(path: string) {
	const metadata = await lstat(path).catch(() => undefined);
	return metadata?.isDirectory() === true;
}

/**
 * Linux keeps the pinned legacy Landlock backend, which refuses a permission
 * profile requiring direct runtime enforcement. The deployment's trusted
 * `setpriv` therefore applies the boundary to the whole native process instead.
 * Landlock rules only ever add access, so an allowlist is the only way to
 * exclude a sibling Conversation; Landlock rulesets stack, so pinned Codex still
 * applies its own policy to tool children beneath this one.
 */
async function conversationLandlockArguments(
	executable: string,
	launchPath: string | undefined,
	policy: ConversationLaunchPolicy,
) {
	const rules: string[] = [];
	const allow = async (rights: string, path: string) => {
		if (!(await existingDirectory(path))) return;
		rules.push("--landlock-rule", `path-beneath:${rights}:${path}`);
	};
	// The pinned release and its bundled resources stay read-only.
	await allow(landlockProgramRights, dirname(dirname(executable)));
	for (const entry of (launchPath ?? "").split(delimiter)) {
		if (entry) await allow(landlockProgramRights, entry);
	}
	for (const path of ["/bin", "/sbin", "/usr", "/lib", "/lib64"]) {
		await allow(landlockProgramRights, path);
	}
	for (const path of ["/etc", "/proc", "/sys"]) {
		await allow(landlockMetadataRights, path);
	}
	await allow(landlockDataRights, "/dev");
	// Only this Conversation's durable directory and the ephemeral HOME/TMPDIR.
	const ephemeral = policy.environment.TMPDIR;
	if (ephemeral) await allow(landlockDataRights, ephemeral);
	await allow(landlockDataRights, policy.root);
	if (!rules.includes(`path-beneath:${landlockDataRights}:${policy.root}`)) {
		throw unavailable();
	}
	return [
		"--no-new-privs",
		"--landlock-access",
		`fs:${landlockDataRights}`,
		...rules,
	];
}

/**
 * The platform never routes a native process's loopback traffic through a
 * proxy: the active model endpoint is always loopback, and a host proxy
 * configuration must not intercept it. The launch environment carries no proxy
 * variables of its own, so this only refuses an operating-system proxy.
 */
function loopbackProxyEnvironment() {
	return {
		NO_PROXY: loopbackProxyExclusions,
		no_proxy: loopbackProxyExclusions,
	};
}

interface CommandOutput {
	stdout: string;
	stdoutTooLarge: boolean;
}

type CommandOutcome =
	| { kind: "close"; code: number | null }
	| { kind: "error" };

async function runProbeCommand(
	executable: string,
	args: readonly string[],
	timeoutMs: number,
	captureStdout: boolean,
	launchPolicy: IsolatedLaunchPolicy,
): Promise<CommandOutput> {
	let process: ChildProcess;
	try {
		process = spawn(executable, args, {
			stdio: ["ignore", captureStdout ? "pipe" : "ignore", "ignore"],
			cwd: launchPolicy.directory,
			env: launchPolicy.environment,
		});
	} catch {
		throw unavailable();
	}
	const closed = new Promise<true>((resolve) => {
		process.once("close", () => resolve(true));
	});
	const outcome = new Promise<CommandOutcome>((resolve) => {
		process.once("error", () => resolve({ kind: "error" }));
		process.once("close", (code) => resolve({ kind: "close", code }));
	});
	let stdout = "";
	let stdoutBytes = 0;
	let stdoutTooLarge = false;
	if (captureStdout) {
		if (!process.stdout) {
			await reapChild(process, closed, timeoutMs);
			throw unavailable();
		}
		process.stdout.on("data", (chunk: Buffer) => {
			if (stdoutTooLarge) return;
			if (chunk.byteLength > maximumFrameBytes - stdoutBytes) {
				stdoutTooLarge = true;
				return;
			}
			stdoutBytes += chunk.byteLength;
			stdout += chunk.toString("utf8");
		});
	}
	const result = await waitForResult(outcome, timeoutMs);
	if (!result) {
		await reapChild(process, closed, timeoutMs);
		throw timedOut();
	}
	if (result.kind === "error" || result.code !== 0) {
		await reapChild(process, closed, timeoutMs);
		throw unavailable();
	}
	return { stdout, stdoutTooLarge };
}

async function probeVersion(
	executable: string,
	timeoutMs: number,
	launchPolicy: IsolatedLaunchPolicy,
) {
	const output = await runProbeCommand(
		executable,
		["--version"],
		timeoutMs,
		true,
		launchPolicy,
	);
	if (
		output.stdoutTooLarge ||
		output.stdout.trim() !==
			`codex-cli ${CODEX_APP_SERVER_V2_PROVENANCE.codexVersion}`
	) {
		throw provenanceMismatchError();
	}
}

async function verifySchema(
	executable: string,
	timeoutMs: number,
	launchPolicy: IsolatedLaunchPolicy,
) {
	let directory: string;
	try {
		directory = await mkdtemp(join(tmpdir(), "agent-runtime-codex-schema-"));
	} catch {
		throw unavailable();
	}
	let failure: CodexAppServerBridgeError | undefined;
	try {
		await runProbeCommand(
			executable,
			["app-server", "generate-json-schema", "--out", directory],
			timeoutMs,
			false,
			launchPolicy,
		);
		const schema = await readFile(join(directory, schemaArtifactName));
		const digest = `sha256:${createHash("sha256").update(schema).digest("hex")}`;
		if (digest !== CODEX_APP_SERVER_V2_PROVENANCE.schemaSha256) {
			failure = provenanceMismatchError();
		}
	} catch (error) {
		failure =
			error instanceof CodexAppServerBridgeError
				? error
				: provenanceMismatchError();
	}
	try {
		await rm(directory, { recursive: true, force: true });
	} catch {
		failure ??= unavailable();
	}
	if (failure) throw failure;
}

async function verifyLinuxSandbox(
	launchPolicy: IsolatedLaunchPolicy,
	timeoutMs: number,
) {
	if (platform !== "linux") return;
	try {
		const helper = await resolveExecutable(
			launchPolicy.environment.PATH,
			"setpriv",
		);
		// ABI V5's newest filesystem right must install without BestEffort masking.
		// setpriv fails if the kernel or container policy cannot enforce the rule.
		await runProbeCommand(
			helper,
			[
				"--no-new-privs",
				"--landlock-access",
				"fs:ioctl-dev",
				"--",
				"/bin/true",
			],
			timeoutMs,
			false,
			launchPolicy,
		);
	} catch {
		throw new CodexAppServerBridgeError(
			"CODEX_APP_SERVER_SANDBOX_UNAVAILABLE",
			"Codex requires setpriv and enforceable Landlock ABI V5 filesystem rights",
		);
	}
}

function provenanceMismatchError() {
	return new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_PROVENANCE_MISMATCH",
		"Codex app-server provenance does not match the pinned release",
	);
}

export class CodexAppServerBridge {
	#queue = new FrameQueue();
	#exit: Promise<void>;
	#resolveExit!: () => void;
	#output = Buffer.alloc(0);
	#failure?: CodexAppServerBridgeError;
	#closing = false;
	#isClosed = false;
	#reaping?: Promise<void>;
	#cleaning?: Promise<void>;
	#process: ChildProcessWithoutNullStreams;
	#shutdownTimeoutMs: number;

	private constructor(
		process: ChildProcessWithoutNullStreams,
		shutdownTimeoutMs: number,
		private readonly isolatedDirectory: string,
	) {
		this.#process = process;
		this.#shutdownTimeoutMs = shutdownTimeoutMs;
		this.#exit = new Promise((resolve) => {
			this.#resolveExit = resolve;
		});
		process.stderr.resume();
		process.stdout.on("data", (chunk: Buffer) => this.receive(chunk));
		process.stdin.on("error", () => this.fail(exited()));
		process.once("error", () => this.fail(unavailable()));
		process.once("close", () => {
			this.#isClosed = true;
			this.#resolveExit();
			if (this.#closing) this.#queue.finish();
			else this.fail(exited());
			void this.cleanIsolatedDirectory();
		});
	}

	static async open(options: CodexAppServerBridgeOptions) {
		const validated = validateOptions(options);
		const launchPath = validated.launchPath ?? env.PATH;
		const executable = await resolveExecutable(launchPath, "codex");
		const launchPolicy = await createIsolatedLaunchPolicy(launchPath);
		let nativeLaunchPolicy: ConversationLaunchPolicy;
		let boundary: string[];
		try {
			await probeVersion(executable, validated.startupTimeoutMs, launchPolicy);
			await verifySchema(executable, validated.startupTimeoutMs, launchPolicy);
			await verifyLinuxSandbox(launchPolicy, validated.startupTimeoutMs);
			nativeLaunchPolicy = await persistentLaunchPolicy(
				validated.dataDirectory,
				validated.conversationKey,
				launchPolicy,
			);
			// A platform without an enforceable Conversation boundary never starts a
			// native process; there is no unrestricted fallback.
			if (platform === "linux") {
				const helper = await resolveExecutable(launchPath, "setpriv");
				boundary = [
					helper,
					...(await conversationLandlockArguments(
						executable,
						launchPath,
						nativeLaunchPolicy,
					)),
					"--",
				];
			} else if (platform === "darwin") {
				boundary = [];
			} else {
				throw new CodexAppServerBridgeError(
					"CODEX_APP_SERVER_SANDBOX_UNAVAILABLE",
					"Codex requires an enforceable Conversation filesystem boundary",
				);
			}
		} catch (error) {
			await removeIsolatedDirectory(launchPolicy.directory);
			throw error;
		}
		const [command = executable, ...boundaryArguments] = boundary;
		let process: ChildProcessWithoutNullStreams;
		try {
			process = spawn(
				command,
				[
					...boundaryArguments,
					...(boundary.length > 0 ? [executable] : []),
					"app-server",
					"--stdio",
					"--strict-config",
					"--config",
					`model=${JSON.stringify(validated.model)}`,
					"--config",
					`model_reasoning_effort=${JSON.stringify(validated.reasoningEffort)}`,
					"--config",
					"mcp_servers={}",
					"--config",
					"features.plugins=false",
					// The owning Conversation keeps a writable workspace on every
					// platform; the boundary above keeps siblings unreachable. Pinned
					// Codex refuses sandbox_mode beside a permissions profile, so each
					// platform states it once.
					...(platform === "linux"
						? [
								"--config",
								'sandbox_mode="workspace-write"',
								// Landlock enforces the native policy without namespace
								// privileges. Admission above requires the full pinned
								// filesystem capability set.
								"--config",
								"features.use_legacy_landlock=true",
							]
						: conversationPermissionArguments(nativeLaunchPolicy)),
					...modelAccessArguments(validated.modelAccess),
				],
				{
					stdio: ["pipe", "pipe", "pipe"],
					cwd: nativeLaunchPolicy.directory,
					env: {
						...nativeLaunchPolicy.environment,
						...loopbackProxyEnvironment(),
						...(validated.modelAccess
							? {
									[modelCredentialEnvironmentKey]:
										validated.modelAccess.credential,
								}
							: {}),
					},
				},
			);
		} catch {
			await removeIsolatedDirectory(launchPolicy.directory);
			throw unavailable();
		}
		const bridge = new CodexAppServerBridge(
			process,
			validated.shutdownTimeoutMs,
			launchPolicy.directory,
		);
		try {
			await bridge.waitForSpawn(validated.startupTimeoutMs);
			return bridge;
		} catch (error) {
			await bridge.close().catch(() => {});
			throw error;
		}
	}

	provenance(): CodexAppServerProvenanceV2 {
		return CODEX_APP_SERVER_V2_PROVENANCE;
	}

	frames(): AsyncIterable<CodexAppServerFrame> {
		return {
			[Symbol.asyncIterator]: () => ({ next: () => this.#queue.next() }),
		};
	}

	async send(frame: CodexAppServerFrame) {
		if (this.#closing || this.#isClosed || this.#failure) throw closed();
		if (!isPlainRecord(frame)) throw invalidFrame();
		let encoded: string;
		try {
			const payload = JSON.stringify(frame);
			if (payload === undefined || !isPlainRecord(JSON.parse(payload))) {
				throw invalidFrame();
			}
			encoded = `${payload}\n`;
		} catch {
			throw invalidFrame();
		}
		if (Buffer.byteLength(encoded) > maximumFrameBytes) throw invalidFrame();
		await new Promise<void>((resolve, reject) => {
			let settled = false;
			const rejectExited = () => {
				const error = exited();
				this.fail(error);
				reject(error);
			};
			const settle = (work: () => void) => {
				if (settled) return;
				settled = true;
				this.#process.stdin.off("error", onWriteError);
				work();
			};
			const onWriteError = () => settle(rejectExited);
			this.#process.stdin.once("error", onWriteError);
			try {
				this.#process.stdin.write(encoded, (error) => {
					if (error) settle(rejectExited);
					else settle(resolve);
				});
			} catch {
				settle(rejectExited);
			}
		});
	}

	async close() {
		if (this.#isClosed) {
			await this.cleanIsolatedDirectory();
			return;
		}
		if (this.#reaping) {
			await this.#reaping;
			await this.cleanIsolatedDirectory();
			return;
		}
		if (this.#closing) {
			await this.#exit;
			await this.cleanIsolatedDirectory();
			return;
		}
		this.#closing = true;
		try {
			this.#process.stdin.end();
		} catch {
			kill(this.#process);
		}
		try {
			await this.waitForExit(this.#shutdownTimeoutMs);
		} catch {
			await this.reapOwnedChild();
			throw timedOut();
		} finally {
			await this.cleanIsolatedDirectory();
		}
	}

	private async waitForSpawn(timeoutMs: number) {
		if (this.#isClosed || this.#failure) throw this.#failure ?? exited();
		await new Promise<void>((resolve, reject) => {
			let settled = false;
			const settle = (work: () => void) => {
				if (settled) return;
				settled = true;
				clearTimeout(timer);
				work();
			};
			const timer = setTimeout(() => {
				void this.reapOwnedChild().then(() => settle(() => reject(timedOut())));
			}, timeoutMs);
			this.#process.once("spawn", () => settle(resolve));
			this.#process.once("error", () => settle(() => reject(unavailable())));
			this.#process.once("close", () => settle(() => reject(exited())));
		});
	}

	private async waitForExit(timeoutMs: number) {
		let timer: ReturnType<typeof setTimeout> | undefined;
		try {
			await Promise.race([
				this.#exit,
				new Promise<never>((_, reject) => {
					timer = setTimeout(() => reject(timedOut()), timeoutMs);
				}),
			]);
		} finally {
			if (timer) clearTimeout(timer);
		}
	}

	private receive(chunk: Buffer) {
		if (this.#failure || this.#isClosed) return;
		let remaining = chunk;
		while (remaining.byteLength > 0) {
			const newline = remaining.indexOf(0x0a);
			if (newline === -1) {
				if (
					remaining.byteLength >
					maximumFrameBytes - this.#output.byteLength
				) {
					this.fail(invalidFrame());
					return;
				}
				this.#output = Buffer.concat([this.#output, remaining]);
				return;
			}
			const line = remaining.subarray(0, newline);
			remaining = remaining.subarray(newline + 1);
			if (line.byteLength > maximumFrameBytes - this.#output.byteLength) {
				this.fail(invalidFrame());
				return;
			}
			const frame =
				this.#output.byteLength === 0
					? line
					: Buffer.concat([this.#output, line]);
			this.#output = Buffer.alloc(0);
			if (frame.byteLength > maximumFrameBytes) {
				this.fail(invalidFrame());
				return;
			}
			const json = frame.at(-1) === 0x0d ? frame.subarray(0, -1) : frame;
			try {
				const value = JSON.parse(utf8.decode(json)) as unknown;
				if (!isPlainRecord(value) || !this.#queue.push(value)) {
					this.fail(invalidFrame());
					return;
				}
			} catch {
				this.fail(invalidFrame());
				return;
			}
		}
	}

	private fail(error: CodexAppServerBridgeError) {
		if (this.#failure) return;
		this.#failure = error;
		this.#queue.fail(error);
		void this.reapOwnedChild();
	}

	private async reapOwnedChild() {
		if (this.#isClosed) return;
		if (this.#reaping) return this.#reaping;
		this.#closing = true;
		this.#reaping = (async () => {
			kill(this.#process);
			try {
				await this.waitForExit(this.#shutdownTimeoutMs);
				return;
			} catch {
				kill(this.#process, "SIGKILL");
				try {
					await this.waitForExit(this.#shutdownTimeoutMs);
				} catch {
					// The process could not be reaped within the bounded cleanup window.
				}
			}
		})();
		return this.#reaping;
	}

	private cleanIsolatedDirectory() {
		if (!this.#isClosed) return Promise.resolve();
		this.#cleaning ??= removeIsolatedDirectory(this.isolatedDirectory);
		return this.#cleaning;
	}
}
