import {
	type ChildProcess,
	type ChildProcessWithoutNullStreams,
	spawn,
} from "node:child_process";
import { TextDecoder } from "node:util";

const defaultTimeoutMs = 5_000;
const maximumTimeoutMs = 30_000;
const minimumTimeoutMs = 25;
const maximumFrameBytes = 65_536;
const maximumQueuedFrames = 256;
const modelPattern = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const reasoningEffortPattern = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;
const sha256Pattern = /^sha256:[a-f0-9]{64}$/;
const utf8 = new TextDecoder("utf-8", { fatal: true });

export interface CodexAppServerProvenanceV2 {
	readonly protocolVersion: 2;
	readonly codexVersion: string;
	readonly upstreamTag: string;
	readonly upstreamCommit: string;
	readonly schemaSha256: string;
}

// Generated by codex app-server generate-json-schema from the pinned release.
export const CODEX_APP_SERVER_V2_PROVENANCE = Object.freeze({
	protocolVersion: 2 as const,
	codexVersion: "0.153.0",
	upstreamTag: "rust-v0.153.0",
	upstreamCommit: "41e22fee981a63b3698df7ed36bad393cda24715",
	schemaSha256:
		"sha256:d3eace08be5dca386bfd1f1e8df650058b4113f1e10870a284d775d75517576a",
});

export type CodexAppServerFrame = Readonly<Record<string, unknown>>;

export interface CodexAppServerBridgeOptions {
	readonly model: string;
	readonly reasoningEffort: string;
	readonly provenance: CodexAppServerProvenanceV2;
	readonly startupTimeoutMs?: number;
	readonly shutdownTimeoutMs?: number;
}

type CodexAppServerBridgeErrorCode =
	| "CODEX_APP_SERVER_CONFIGURATION_INVALID"
	| "CODEX_APP_SERVER_PROVENANCE_MISMATCH"
	| "CODEX_APP_SERVER_UNAVAILABLE"
	| "CODEX_APP_SERVER_TIMEOUT"
	| "CODEX_APP_SERVER_EXITED"
	| "CODEX_APP_SERVER_FRAME_INVALID"
	| "CODEX_APP_SERVER_CLOSED";

export class CodexAppServerBridgeError extends Error {
	readonly retryable: boolean;

	constructor(
		readonly code: CodexAppServerBridgeErrorCode,
		message: string,
		retryable = false,
	) {
		super(message);
		this.name = "CodexAppServerBridgeError";
		this.retryable = retryable;
	}
}

interface ValidatedOptions {
	model: string;
	reasoningEffort: string;
	startupTimeoutMs: number;
	shutdownTimeoutMs: number;
}

interface QueueWaiter {
	resolve: (value: IteratorResult<CodexAppServerFrame>) => void;
	reject: (reason: CodexAppServerBridgeError) => void;
}

class FrameQueue {
	private readonly values: CodexAppServerFrame[] = [];
	private readonly waiters: QueueWaiter[] = [];
	private failure?: CodexAppServerBridgeError;
	private finished = false;

	push(value: CodexAppServerFrame) {
		if (this.finished || this.failure) return false;
		const waiter = this.waiters.shift();
		if (waiter) {
			waiter.resolve({ done: false, value });
			return true;
		}
		if (this.values.length >= maximumQueuedFrames) return false;
		this.values.push(value);
		return true;
	}

	fail(error: CodexAppServerBridgeError) {
		if (this.finished || this.failure) return;
		this.failure = error;
		for (const waiter of this.waiters.splice(0)) waiter.reject(error);
	}

	finish() {
		if (this.finished || this.failure) return;
		this.finished = true;
		for (const waiter of this.waiters.splice(0)) {
			waiter.resolve({ done: true, value: undefined });
		}
	}

	next(): Promise<IteratorResult<CodexAppServerFrame>> {
		const value = this.values.shift();
		if (value) return Promise.resolve({ done: false, value });
		if (this.failure) return Promise.reject(this.failure);
		if (this.finished) return Promise.resolve({ done: true, value: undefined });
		return new Promise((resolve, reject) =>
			this.waiters.push({ resolve, reject }),
		);
	}
}

function configurationInvalid(): never {
	throw new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_CONFIGURATION_INVALID",
		"Codex app-server configuration is invalid",
	);
}

function provenanceMismatch(): never {
	throw new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_PROVENANCE_MISMATCH",
		"Codex app-server provenance does not match the pinned release",
	);
}

function unavailable() {
	return new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_UNAVAILABLE",
		"Codex app-server is unavailable",
		true,
	);
}

function timedOut() {
	return new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_TIMEOUT",
		"Codex app-server did not respond before the configured timeout",
		true,
	);
}

function exited() {
	return new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_EXITED",
		"Codex app-server exited unexpectedly",
		true,
	);
}

function invalidFrame() {
	return new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_FRAME_INVALID",
		"Codex app-server emitted an invalid frame",
	);
}

function closed() {
	return new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_CLOSED",
		"Codex app-server bridge is closed",
	);
}

function isPlainRecord(value: unknown): value is Record<string, unknown> {
	return (
		typeof value === "object" &&
		value !== null &&
		!Array.isArray(value) &&
		Object.getPrototypeOf(value) === Object.prototype
	);
}

function exactKeys(value: Record<string, unknown>, keys: readonly string[]) {
	return (
		Object.keys(value).length === keys.length &&
		Object.keys(value).every((key) => keys.includes(key))
	);
}

function hasPinnedProvenance(
	value: unknown,
): value is CodexAppServerProvenanceV2 {
	if (
		!isPlainRecord(value) ||
		!exactKeys(value, [
			"protocolVersion",
			"codexVersion",
			"upstreamTag",
			"upstreamCommit",
			"schemaSha256",
		]) ||
		value.protocolVersion !== 2 ||
		typeof value.codexVersion !== "string" ||
		typeof value.upstreamTag !== "string" ||
		typeof value.upstreamCommit !== "string" ||
		typeof value.schemaSha256 !== "string" ||
		!sha256Pattern.test(value.schemaSha256)
	) {
		return false;
	}
	return (
		value.codexVersion === CODEX_APP_SERVER_V2_PROVENANCE.codexVersion &&
		value.upstreamTag === CODEX_APP_SERVER_V2_PROVENANCE.upstreamTag &&
		value.upstreamCommit === CODEX_APP_SERVER_V2_PROVENANCE.upstreamCommit &&
		value.schemaSha256 === CODEX_APP_SERVER_V2_PROVENANCE.schemaSha256
	);
}

function parseTimeout(value: unknown, fallback: number) {
	if (value === undefined) return fallback;
	if (
		typeof value !== "number" ||
		!Number.isSafeInteger(value) ||
		value < minimumTimeoutMs ||
		value > maximumTimeoutMs
	) {
		configurationInvalid();
	}
	return value;
}

function validateOptions(input: unknown): ValidatedOptions {
	if (!isPlainRecord(input)) configurationInvalid();
	const allowedKeys = [
		"model",
		"reasoningEffort",
		"provenance",
		"startupTimeoutMs",
		"shutdownTimeoutMs",
	];
	if (!Object.keys(input).every((key) => allowedKeys.includes(key))) {
		configurationInvalid();
	}
	if (
		typeof input.model !== "string" ||
		!modelPattern.test(input.model) ||
		typeof input.reasoningEffort !== "string" ||
		!reasoningEffortPattern.test(input.reasoningEffort)
	) {
		configurationInvalid();
	}
	if (!hasPinnedProvenance(input.provenance)) provenanceMismatch();
	return {
		model: input.model,
		reasoningEffort: input.reasoningEffort,
		startupTimeoutMs: parseTimeout(input.startupTimeoutMs, defaultTimeoutMs),
		shutdownTimeoutMs: parseTimeout(input.shutdownTimeoutMs, defaultTimeoutMs),
	};
}

function kill(
	process: Pick<ChildProcess, "kill">,
	signal: "SIGTERM" | "SIGKILL" = "SIGTERM",
) {
	try {
		process.kill(signal);
	} catch {
		// The process already exited.
	}
}

function probeVersion(timeoutMs: number): Promise<void> {
	let process: ReturnType<typeof spawn>;
	try {
		process = spawn("codex", ["--version"], {
			stdio: ["ignore", "pipe", "pipe"],
		});
	} catch {
		return Promise.reject(unavailable());
	}
	const stdout = process.stdout;
	const stderr = process.stderr;
	if (!stdout || !stderr) {
		kill(process);
		return Promise.reject(unavailable());
	}
	stderr.resume();
	return new Promise((resolve, reject) => {
		let output = "";
		let outputBytes = 0;
		let outputTooLarge = false;
		let settled = false;
		const settle = (work: () => void) => {
			if (settled) return;
			settled = true;
			clearTimeout(timer);
			work();
		};
		const timer = setTimeout(() => {
			kill(process);
			settle(() => reject(timedOut()));
		}, timeoutMs);
		stdout.on("data", (chunk: Buffer) => {
			if (outputTooLarge) return;
			if (chunk.byteLength > maximumFrameBytes - outputBytes) {
				outputTooLarge = true;
				return;
			}
			outputBytes += chunk.byteLength;
			output += chunk.toString("utf8");
		});
		process.once("error", () => settle(() => reject(unavailable())));
		process.once("close", (code) => {
			if (
				code !== 0 ||
				outputTooLarge ||
				output.trim() !==
					`codex-cli ${CODEX_APP_SERVER_V2_PROVENANCE.codexVersion}`
			) {
				settle(() =>
					reject(
						output.length === 0 ? unavailable() : provenanceMismatchError(),
					),
				);
				return;
			}
			settle(resolve);
		});
	});
}

function provenanceMismatchError() {
	return new CodexAppServerBridgeError(
		"CODEX_APP_SERVER_PROVENANCE_MISMATCH",
		"Codex app-server provenance does not match the pinned release",
	);
}

export class CodexAppServerBridge {
	#queue = new FrameQueue();
	#exit: Promise<void>;
	#resolveExit!: () => void;
	#output = Buffer.alloc(0);
	#failure?: CodexAppServerBridgeError;
	#closing = false;
	#isClosed = false;
	#process: ChildProcessWithoutNullStreams;
	#shutdownTimeoutMs: number;

	private constructor(
		process: ChildProcessWithoutNullStreams,
		shutdownTimeoutMs: number,
	) {
		this.#process = process;
		this.#shutdownTimeoutMs = shutdownTimeoutMs;
		this.#exit = new Promise((resolve) => {
			this.#resolveExit = resolve;
		});
		process.stderr.resume();
		process.stdout.on("data", (chunk: Buffer) => this.receive(chunk));
		process.once("error", () => this.fail(unavailable()));
		process.once("close", () => {
			this.#isClosed = true;
			this.#resolveExit();
			if (this.#closing) this.#queue.finish();
			else this.fail(exited());
		});
	}

	static async open(options: CodexAppServerBridgeOptions) {
		const validated = validateOptions(options);
		await probeVersion(validated.startupTimeoutMs);
		let process: ChildProcessWithoutNullStreams;
		try {
			process = spawn(
				"codex",
				[
					"app-server",
					"--stdio",
					"--strict-config",
					"--config",
					`model=${JSON.stringify(validated.model)}`,
					"--config",
					`model_reasoning_effort=${JSON.stringify(validated.reasoningEffort)}`,
				],
				{ stdio: ["pipe", "pipe", "pipe"] },
			);
		} catch {
			throw unavailable();
		}
		const bridge = new CodexAppServerBridge(
			process,
			validated.shutdownTimeoutMs,
		);
		await bridge.waitForSpawn(validated.startupTimeoutMs);
		return bridge;
	}

	provenance(): CodexAppServerProvenanceV2 {
		return CODEX_APP_SERVER_V2_PROVENANCE;
	}

	frames(): AsyncIterable<CodexAppServerFrame> {
		return {
			[Symbol.asyncIterator]: () => ({ next: () => this.#queue.next() }),
		};
	}

	async send(frame: CodexAppServerFrame) {
		if (this.#closing || this.#isClosed || this.#failure) throw closed();
		if (!isPlainRecord(frame)) throw invalidFrame();
		let encoded: string;
		try {
			encoded = `${JSON.stringify(frame)}\n`;
		} catch {
			throw invalidFrame();
		}
		if (Buffer.byteLength(encoded) > maximumFrameBytes) throw invalidFrame();
		await new Promise<void>((resolve, reject) => {
			try {
				this.#process.stdin.write(encoded, (error) => {
					if (error) reject(exited());
					else resolve();
				});
			} catch {
				reject(exited());
			}
		});
	}

	async close() {
		if (this.#isClosed) return;
		if (this.#closing) return this.#exit;
		this.#closing = true;
		try {
			this.#process.stdin.end();
		} catch {
			kill(this.#process);
		}
		try {
			await this.waitForExit(this.#shutdownTimeoutMs);
		} catch {
			kill(this.#process);
			try {
				await this.waitForExit(this.#shutdownTimeoutMs);
			} catch {
				kill(this.#process, "SIGKILL");
				try {
					await this.waitForExit(this.#shutdownTimeoutMs);
				} catch {
					throw timedOut();
				}
			}
			throw timedOut();
		}
	}

	private async waitForSpawn(timeoutMs: number) {
		if (this.#isClosed || this.#failure) throw this.#failure ?? exited();
		await new Promise<void>((resolve, reject) => {
			let settled = false;
			const settle = (work: () => void) => {
				if (settled) return;
				settled = true;
				clearTimeout(timer);
				work();
			};
			const timer = setTimeout(() => {
				kill(this.#process);
				settle(() => reject(timedOut()));
			}, timeoutMs);
			this.#process.once("spawn", () => settle(resolve));
			this.#process.once("error", () => settle(() => reject(unavailable())));
			this.#process.once("close", () => settle(() => reject(exited())));
		});
	}

	private async waitForExit(timeoutMs: number) {
		let timer: ReturnType<typeof setTimeout> | undefined;
		try {
			await Promise.race([
				this.#exit,
				new Promise<never>((_, reject) => {
					timer = setTimeout(() => reject(timedOut()), timeoutMs);
				}),
			]);
		} finally {
			if (timer) clearTimeout(timer);
		}
	}

	private receive(chunk: Buffer) {
		if (this.#failure || this.#isClosed) return;
		let remaining = chunk;
		while (remaining.byteLength > 0) {
			const newline = remaining.indexOf(0x0a);
			if (newline === -1) {
				if (
					remaining.byteLength >
					maximumFrameBytes - this.#output.byteLength
				) {
					this.fail(invalidFrame());
					return;
				}
				this.#output = Buffer.concat([this.#output, remaining]);
				return;
			}
			const line = remaining.subarray(0, newline);
			remaining = remaining.subarray(newline + 1);
			if (line.byteLength > maximumFrameBytes - this.#output.byteLength) {
				this.fail(invalidFrame());
				return;
			}
			const frame =
				this.#output.byteLength === 0
					? line
					: Buffer.concat([this.#output, line]);
			this.#output = Buffer.alloc(0);
			if (frame.byteLength > maximumFrameBytes) {
				this.fail(invalidFrame());
				return;
			}
			const json = frame.at(-1) === 0x0d ? frame.subarray(0, -1) : frame;
			try {
				const value = JSON.parse(utf8.decode(json)) as unknown;
				if (!isPlainRecord(value) || !this.#queue.push(value)) {
					this.fail(invalidFrame());
					return;
				}
			} catch {
				this.fail(invalidFrame());
				return;
			}
		}
	}

	private fail(error: CodexAppServerBridgeError) {
		if (this.#failure) return;
		this.#failure = error;
		this.#queue.fail(error);
	}
}
