ALTER TYPE "platform"."conversation_execution_status" ADD VALUE 'waiting' BEFORE 'submitted';--> statement-breakpoint
ALTER TABLE "platform"."conversation_executions" ADD COLUMN "principal_type" varchar(16) DEFAULT 'user' NOT NULL;--> statement-breakpoint
ALTER TABLE "platform"."conversation_executions" ADD COLUMN "task_wait_order" bigint;--> statement-breakpoint
ALTER TABLE "platform"."conversation_executions" ADD COLUMN "task_wait_deadline" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "platform"."conversations" ADD COLUMN "principal_type" varchar(16) DEFAULT 'user' NOT NULL;--> statement-breakpoint
ALTER TABLE "platform"."conversations" ADD CONSTRAINT "conversation_principal_binding_unique" UNIQUE("id","agent_id","actor_id","channel_id","principal_type");--> statement-breakpoint
ALTER TABLE "platform"."conversation_executions" ADD CONSTRAINT "conversation_execution_principal_binding_fk" FOREIGN KEY ("conversation_id","agent_id","actor_id","channel_id","principal_type") REFERENCES "platform"."conversations"("id","agent_id","actor_id","channel_id","principal_type") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "platform"."conversation_executions" ADD CONSTRAINT "conversation_execution_principal_type_valid" CHECK (("platform"."conversation_executions"."principal_type" = 'user' AND "platform"."conversation_executions"."channel_id" <> 'api:application') OR ("platform"."conversation_executions"."principal_type" = 'application' AND "platform"."conversation_executions"."channel_id" in ('api', 'api:application')));--> statement-breakpoint
ALTER TABLE "platform"."conversation_executions" ADD CONSTRAINT "conversation_execution_task_wait_binding" CHECK (("platform"."conversation_executions"."task_wait_order" IS NULL AND "platform"."conversation_executions"."task_wait_deadline" IS NULL AND "platform"."conversation_executions"."status"::text <> 'waiting') OR ("platform"."conversation_executions"."task_wait_order" IS NOT NULL AND "platform"."conversation_executions"."task_wait_order" between 1 and 9007199254740991 AND "platform"."conversation_executions"."task_wait_deadline" IS NOT NULL AND "platform"."conversation_executions"."task_wait_deadline" > "platform"."conversation_executions"."created_at"));--> statement-breakpoint
ALTER TABLE "platform"."conversations" ADD CONSTRAINT "conversation_principal_type_valid" CHECK (("platform"."conversations"."principal_type" = 'user' AND "platform"."conversations"."channel_id" <> 'api:application') OR ("platform"."conversations"."principal_type" = 'application' AND "platform"."conversations"."channel_id" in ('api', 'api:application')));