import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
	chmod,
	lstat,
	mkdtemp,
	readdir,
	readFile,
	realpath,
	rename,
	rm,
	stat,
	symlink,
	writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { SkillPackagePublicationObjectV1 } from "@agent-infra/platform-core";
import { afterEach, describe, expect, it, vi } from "vitest";
import { startMinioFileFixtureV1 } from "./minio.test-support.ts";
import {
	packSkillProjectSnapshotV1,
	prepareSkillPackageV1,
} from "./skill-package-admission.js";
import { SkillPackageMaterializerV1 } from "./skill-package-materializer.js";

// Fixed ZIP generated by Python zipfile, containing SKILL.md and one reference.
const archive = Buffer.from(
	"UEsDBBQAAAAAAAAAIVAu8ee/CgAAAAoAAAAIAAAAU0tJTEwubWQjIFN1bW1hcnkKUEsDBBQAAAAAAAAAIVAE5Me2CgAAAAoAAAAVAAAAcmVmZXJlbmNlcy9yZWFkbWUudHh0cmVmZXJlbmNlClBLAQIUAxQAAAAAAAAAIVAu8ee/CgAAAAoAAAAIAAAAAAAAAAAAAACkgQAAAABTS0lMTC5tZFBLAQIUAxQAAAAAAAAAIVAE5Me2CgAAAAoAAAAVAAAAAAAAAAAAAACkgTAAAAByZWZlcmVuY2VzL3JlYWRtZS50eHRQSwUGAAAAAAIAAgB5AAAAbQAAAAAA",
	"base64",
);
const sha = (bytes: Uint8Array) =>
	createHash("sha256").update(bytes).digest("hex");
const prepared = prepareSkillPackageV1({
	archiveBytes: archive,
	name: "workspace-summary",
	version: "1.0.0",
});
const selection = {
	name: "workspace-summary",
	version: "1.0.0",
	packageDigest: sha(archive),
	manifestDigest: sha(prepared.manifestBytes),
	packageObject: {
		objectRef: "11111111-1111-4111-8111-111111111111",
		version: "opaque/s3+version",
		etag: "etag-1",
		sizeBytes: archive.length,
		mediaType: "application/zip",
		sha256: sha(archive),
	},
};
const roots: string[] = [];
async function root() {
	const path = await realpath(
		await mkdtemp(join(tmpdir(), "skill-materializer-")),
	);
	roots.push(path);
	return path;
}
async function makeWritable(path: string): Promise<void> {
	await chmod(path, 0o700);
	for (const entry of await readdir(path, { withFileTypes: true }))
		if (entry.isDirectory()) await makeWritable(join(path, entry.name));
}
afterEach(async () => {
	for (const path of roots.splice(0)) {
		if ((await lstat(path)).isSymbolicLink()) {
			await rm(path);
			continue;
		}
		await makeWritable(path);
		await rm(path, { recursive: true, force: true });
	}
});
function materializer(assemblyRoot: string) {
	return new SkillPackageMaterializerV1({
		assemblyRoot,
		runtimeUid: 65534,
		readPackage: async (object: SkillPackagePublicationObjectV1) => ({
			...object,
			bytes: archive,
		}),
		verifyAdmission: async () => {},
	});
}
function project(assemblyRoot: string, generationId: string) {
	return join(assemblyRoot, "generations", generationId);
}

describe("Skill package materializer", () => {
	it("publishes one complete immutable generation and retains fixed object references", async () => {
		const assemblyRoot = await root();
		const adapter = materializer(assemblyRoot);
		const result = await adapter.materialize({ packages: [selection] });
		expect(result).toMatchObject({
			schemaVersion: 1,
			status: "materialized",
			packages: [selection],
		});
		expect(result).not.toHaveProperty("readOnly");
		expect(result).not.toHaveProperty("available");
		expect(await adapter.readCurrent()).toEqual(result);
		const directory = project(assemblyRoot, result.generationId);
		expect(
			await readFile(
				join(directory, ".agents/skills/workspace-summary/SKILL.md"),
				"utf8",
			),
		).toBe("# Summary\n");
		expect(
			await readFile(join(directory, ".agents/SKILLS.md"), "utf8"),
		).toContain("workspace-summary@1.0.0");
		expect(
			(await stat(join(directory, ".agents/skills/workspace-summary/SKILL.md")))
				.mode & 0o777,
		).toBe(0o444);
		expect((await stat(directory)).mode & 0o777).toBe(0o555);
	});
});

async function selectionFor(version: string) {
	const value = prepareSkillPackageV1({
		archiveBytes: archive,
		name: selection.name,
		version,
	});
	return { ...selection, version, manifestDigest: sha(value.manifestBytes) };
}

it.each(["before", "after"])(
	"reopens a complete generation after process exit %s the CURRENT switch",
	async (timing) => {
		const assemblyRoot = await root();
		const adapter = materializer(assemblyRoot);
		const original = await adapter.materialize({ packages: [selection] });
		const upgraded = await selectionFor("2.0.0");
		const moduleUrl = new URL("../dist/index.mjs", import.meta.url).href;
		const script = `
 import fs from 'node:fs/promises';
 import {syncBuiltinESMExports} from 'node:module';
 const original=fs.rename;
 fs.rename=async(source,target)=>{
  if(target.endsWith('/CURRENT.json') && process.env.EXIT_AT==='before')process.exit(86);
  await original(source,target);
  if(target.endsWith('/CURRENT.json') && process.env.EXIT_AT==='after')process.exit(86);
 };
 syncBuiltinESMExports();
 const {SkillPackageMaterializerV1}=await import(process.env.MATERIALIZER_MODULE);
 const input=JSON.parse(process.env.PACKAGE_SELECTION);
 const adapter=new SkillPackageMaterializerV1({assemblyRoot:process.env.ASSEMBLY_ROOT,runtimeUid:65534,
  verifyAdmission:async()=>{},readPackage:async object=>({...object,bytes:Buffer.from(process.env.ARCHIVE,'base64')})});
 await adapter.materialize({packages:[input]});`;
		const child = spawnSync(
			process.execPath,
			["--input-type=module", "-e", script],
			{
				env: {
					...process.env,
					EXIT_AT: timing,
					MATERIALIZER_MODULE: moduleUrl,
					PACKAGE_SELECTION: JSON.stringify(upgraded),
					ASSEMBLY_ROOT: assemblyRoot,
					ARCHIVE: archive.toString("base64"),
				},
				timeout: 10000,
				encoding: "utf8",
			},
		);
		expect(child.status, child.stderr).toBe(86);
		const restarted = materializer(assemblyRoot);
		const current = await restarted.readCurrent();
		expect(current?.packages[0]?.version).toBe(
			timing === "before" ? "1.0.0" : "2.0.0",
		);
		expect(
			await readFile(
				join(project(assemblyRoot, original.generationId), ".agents/SKILLS.md"),
				"utf8",
			),
		).toContain("workspace-summary@1.0.0");
		const retried = await restarted.materialize({ packages: [upgraded] });
		expect(await restarted.readCurrent()).toEqual(retried);
		expect(
			await readFile(
				join(project(assemblyRoot, retried.generationId), ".agents/SKILLS.md"),
				"utf8",
			),
		).toContain("workspace-summary@2.0.0");
	},
	15000,
);

it("keeps the previous generation on invalid objects, failed admission and an interrupted read", async () => {
	const assemblyRoot = await root();
	const adapter = materializer(assemblyRoot);
	const original = await adapter.materialize({ packages: [selection] });
	const upgraded = await selectionFor("2.0.0");
	await expect(
		adapter.materialize({
			packages: [{ ...upgraded, manifestDigest: "f".repeat(64) }],
		}),
	).rejects.toMatchObject({ code: "conflict" });
	const denied = new SkillPackageMaterializerV1({
		assemblyRoot,
		runtimeUid: 65534,
		readPackage: async (o) => ({ ...o, bytes: archive }),
		verifyAdmission: async () => {
			throw new Error("admission expired");
		},
	});
	await expect(
		denied.materialize({ packages: [upgraded] }),
	).rejects.toMatchObject({ code: "unavailable" });
	const otherObject = new SkillPackageMaterializerV1({
		assemblyRoot,
		runtimeUid: 65534,
		readPackage: async (o) => ({
			...o,
			objectRef: "22222222-2222-4222-8222-222222222222",
			bytes: archive,
		}),
		verifyAdmission: async () => {},
	});
	await expect(
		otherObject.materialize({ packages: [upgraded] }),
	).rejects.toMatchObject({ code: "conflict" });
	expect(await adapter.readCurrent()).toEqual(original);
});

it("replays a fixed generation, retains historical content and supports an empty set", async () => {
	const assemblyRoot = await root();
	const adapter = materializer(assemblyRoot);
	const original = await adapter.materialize({ packages: [selection] });
	expect(
		await adapter.materialize({ packages: [structuredClone(selection)] }),
	).toEqual(original);
	const empty = await adapter.materialize({ packages: [] });
	expect(empty.packages).toEqual([]);
	expect(await adapter.readCurrent()).toEqual(empty);
	expect(
		await readFile(
			join(
				project(assemblyRoot, original.generationId),
				".agents/skills/workspace-summary/SKILL.md",
			),
			"utf8",
		),
	).toBe("# Summary\n");
	expect(
		await readFile(
			join(project(assemblyRoot, empty.generationId), ".agents/SKILLS.md"),
			"utf8",
		),
	).toBe("# Skills\n\n");
});

it("freezes the package list and descriptor before external waits", async () => {
	const assemblyRoot = await root();
	const requested = structuredClone(selection);
	const packages = [requested];
	const adapter = new SkillPackageMaterializerV1({
		assemblyRoot,
		runtimeUid: 65534,
		readPackage: async (object: SkillPackagePublicationObjectV1) => ({
			...object,
			bytes: archive,
		}),
		verifyAdmission: async () => {
			requested.name = "changed";
			requested.packageObject.version = "swapped";
			packages.push(structuredClone(selection));
		},
	});
	const result = await adapter.materialize({ packages });
	expect(result.packages).toEqual([selection]);
	expect(await adapter.readCurrent()).toEqual(result);
});

it.each([
	null,
	{ packages: [null] },
	{ packages: Array(1) },
	{ packages: Array(11).fill(selection) },
	{
		packages: [
			{
				...selection,
				packageObject: { ...selection.packageObject, sizeBytes: 50000001 },
			},
		],
	},
])(
	"rejects malformed or excessive input without reading a package (%#)",
	async (input) => {
		const assemblyRoot = await root();
		const readPackage = vi.fn(async (object) => ({
			...object,
			bytes: archive,
		}));
		const adapter = new SkillPackageMaterializerV1({
			assemblyRoot,
			runtimeUid: 65534,
			readPackage,
			verifyAdmission: async () => {},
		});
		await expect(adapter.materialize(input)).rejects.toMatchObject({
			code: "invalid",
		});
		expect(readPackage).not.toHaveBeenCalled();
		expect(await adapter.readCurrent()).toBeNull();
	},
);

it("rejects accessors, proxies and extra request path fields", async () => {
	const assemblyRoot = await root();
	const adapter = materializer(assemblyRoot);
	const poison = { ...selection };
	Object.defineProperty(poison, "name", {
		enumerable: true,
		get() {
			throw new Error("getter must not run");
		},
	});
	for (const request of [
		{ packages: [poison] },
		{ packages: [new Proxy(selection, {})] },
		{ packages: [selection], projectRoot: "/tmp/other" },
	]) {
		await expect(adapter.materialize(request)).rejects.toMatchObject({
			code: "invalid",
		});
	}
});

it("rejects unprotected assembly roots, shared Runtime identity and root symlinks", async () => {
	const assemblyRoot = await root();
	const link = `${assemblyRoot}-link`;
	roots.push(link);
	await symlink(assemblyRoot, link);
	expect(() => materializer(link)).toThrow();
	const options = {
		assemblyRoot,
		runtimeUid: process.geteuid?.() ?? 0,
		readPackage: async (object: SkillPackagePublicationObjectV1) => ({
			...object,
			bytes: archive,
		}),
		verifyAdmission: async () => {},
	};
	expect(() => new SkillPackageMaterializerV1(options)).toThrow();
	expect(
		() => new SkillPackageMaterializerV1({ ...options, runtimeUid: 0 }),
	).toThrow();
	await chmod(assemblyRoot, 0o777);
	expect(() => materializer(assemblyRoot)).toThrow();
});

it.each(["initial", "publish"])(
	"rejects assembly-root replacement at %s without writing through the symlink",
	async (timing) => {
		const assemblyRoot = await root();
		const outside = await root();
		const original = await materializer(assemblyRoot).materialize({
			packages: [selection],
		});
		await writeFile(join(outside, "sentinel"), "unchanged");
		const moved = `${assemblyRoot}-moved`;
		roots.push(moved);
		const upgraded = await selectionFor("2.0.0");
		const adapter = new SkillPackageMaterializerV1({
			assemblyRoot,
			runtimeUid: 65534,
			readPackage: async (object: SkillPackagePublicationObjectV1) => ({
				...object,
				bytes: archive,
			}),
			verifyAdmission: async () => {
				if (
					(await readdir(join(assemblyRoot, "generations"))).length >
					(timing === "initial" ? 0 : 1)
				) {
					await rename(assemblyRoot, moved);
					await symlink(outside, assemblyRoot);
				}
			},
		});
		await expect(
			adapter.materialize({ packages: [upgraded] }),
		).rejects.toMatchObject({ code: "conflict" });
		expect(await readdir(outside)).toEqual(["sentinel"]);
		expect(await materializer(moved).readCurrent()).toEqual(original);
	},
);

it("refuses modified physical files instead of reporting the selected generation", async () => {
	const assemblyRoot = await root();
	const adapter = materializer(assemblyRoot);
	const result = await adapter.materialize({ packages: [selection] });
	const target = join(
		project(assemblyRoot, result.generationId),
		".agents/skills/workspace-summary/SKILL.md",
	);
	await chmod(target, 0o644);
	await writeFile(target, "# Changed\n");
	await chmod(target, 0o444);
	await expect(adapter.readCurrent()).rejects.toMatchObject({
		code: "conflict",
	});
});

it("materializes bytes downloaded from the admitted fixed MinIO object version", async () => {
	const fixture = await startMinioFileFixtureV1("skill-package");
	try {
		const assemblyRoot = await root();
		const stored = await fixture.storage.upload({
			objectRef: selection.packageObject.objectRef,
			descriptor: {
				name: "skill.zip",
				mediaType: "application/zip",
				sizeBytes: archive.length,
				sha256: sha(archive),
			},
			expiresAt: new Date(Date.now() + 60000).toISOString(),
			body: new ReadableStream({
				start(controller) {
					controller.enqueue(archive);
					controller.close();
				},
			}),
		});
		const selected = {
			...selection,
			packageObject: {
				objectRef: selection.packageObject.objectRef,
				...stored,
			},
		};
		const adapter = new SkillPackageMaterializerV1({
			assemblyRoot,
			runtimeUid: 65534,
			verifyAdmission: async () => {},
			readPackage: async (descriptor) => {
				const stream = await fixture.storage.download({
					...descriptor,
					expiresAt: new Date(Date.now() + 60000).toISOString(),
				});
				return {
					...descriptor,
					bytes: new Uint8Array(await new Response(stream).arrayBuffer()),
				};
			},
		});
		const result = await adapter.materialize({ packages: [selected] });
		expect(result.packages[0]?.packageObject.version).toBe(stored.version);
		expect(await adapter.readCurrent()).toEqual(result);
	} finally {
		await fixture.close();
	}
}, 30000);

it("accepts maximum-size canonical manifests from the governed ZIP file/path limits", async () => {
	const largeArchive = packSkillProjectSnapshotV1([
		{ path: "SKILL.md", bytes: Buffer.from("# Many files\n") },
		...Array.from({ length: 1799 }, (_, index) => ({
			path: `${"a".repeat(200)}/${"b".repeat(200)}/${"c".repeat(80)}${String(index).padStart(10, "0")}`,
			bytes: new Uint8Array(),
		})),
	]);
	const value = prepareSkillPackageV1({
		archiveBytes: largeArchive,
		name: selection.name,
		version: selection.version,
	});
	expect(value.manifestBytes.byteLength).toBeGreaterThan(1000000);
	const largeInput = {
		...selection,
		manifestDigest: sha(value.manifestBytes),
		packageDigest: sha(largeArchive),
		packageObject: {
			...selection.packageObject,
			sizeBytes: largeArchive.length,
			sha256: sha(largeArchive),
		},
	};
	const assemblyRoot = await root();
	const adapter = new SkillPackageMaterializerV1({
		assemblyRoot,
		runtimeUid: 65534,
		readPackage: async (object) => ({ ...object, bytes: largeArchive }),
		verifyAdmission: async () => {},
	});
	const result = await adapter.materialize({ packages: [largeInput] });
	expect(await adapter.readCurrent()).toEqual(result);
}, 30000);

it("keeps the first generation unpublished when its parent directory cannot be persisted", async () => {
	const assemblyRoot = await root();
	const script = `
 import fs from 'node:fs/promises';import {syncBuiltinESMExports} from 'node:module';
 const open=fs.open;
 fs.open=async(path,...args)=>{const handle=await open(path,...args);if(path===process.env.ASSEMBLY_ROOT)handle.sync=async()=>{throw Object.assign(new Error('injected root fsync failure'),{code:'EIO'});};return handle;};syncBuiltinESMExports();
 const {SkillPackageMaterializerV1}=await import(process.env.MATERIALIZER_MODULE);
 const adapter=new SkillPackageMaterializerV1({assemblyRoot:process.env.ASSEMBLY_ROOT,runtimeUid:65534,verifyAdmission:async()=>{},readPackage:async object=>({...object,bytes:Buffer.from(process.env.ARCHIVE,'base64')})});
 try{await adapter.materialize({packages:[JSON.parse(process.env.PACKAGE_SELECTION)]});process.exit(1);}catch(error){process.exit(error.code==='unavailable'?0:2);}
 `;
	const child = spawnSync(
		process.execPath,
		["--input-type=module", "-e", script],
		{
			env: {
				...process.env,
				MATERIALIZER_MODULE: new URL("../dist/index.mjs", import.meta.url).href,
				ASSEMBLY_ROOT: assemblyRoot,
				PACKAGE_SELECTION: JSON.stringify(selection),
				ARCHIVE: archive.toString("base64"),
			},
			timeout: 10000,
			encoding: "utf8",
		},
	);
	expect(child.status, child.stderr).toBe(0);
	const restarted = materializer(assemblyRoot);
	expect(await restarted.readCurrent()).toBeNull();
	const retried = await restarted.materialize({ packages: [selection] });
	expect(await restarted.readCurrent()).toEqual(retried);
}, 15000);

it.each([false, true])(
	"preserves the selected generation after publication failure (cleanup failure: %s)",
	async (cleanupFails) => {
		const assemblyRoot = await root();
		const adapter = materializer(assemblyRoot);
		const original = await adapter.materialize({ packages: [selection] });
		const upgraded = await selectionFor("2.0.0");
		const script = `
 import fs from 'node:fs/promises';import {syncBuiltinESMExports} from 'node:module';
 const rename=fs.rename,chmod=fs.chmod;let cleanupFailed=false;
 fs.rename=async(source,target)=>{if(target.includes('/generations/'))throw Object.assign(new Error('injected filesystem failure'),{code:'EIO'});await rename(source,target);};
 fs.chmod=async(path,mode)=>{if(process.env.CLEANUP_FAILS==='true' && path.includes('/.staging-') && mode===0o700){cleanupFailed=true;throw Object.assign(new Error('injected cleanup failure'),{code:'EACCES'});}await chmod(path,mode);};syncBuiltinESMExports();
 const {SkillPackageMaterializerV1}=await import(process.env.MATERIALIZER_MODULE);
 const adapter=new SkillPackageMaterializerV1({assemblyRoot:process.env.ASSEMBLY_ROOT,runtimeUid:65534,verifyAdmission:async()=>{},readPackage:async object=>({...object,bytes:Buffer.from(process.env.ARCHIVE,'base64')})});
 try{await adapter.materialize({packages:[JSON.parse(process.env.PACKAGE_SELECTION)]});process.exit(1);}catch(error){process.exit(error.code==='unavailable' && cleanupFailed===(process.env.CLEANUP_FAILS==='true')?0:2);}
 `;
		const child = spawnSync(
			process.execPath,
			["--input-type=module", "-e", script],
			{
				env: {
					...process.env,
					CLEANUP_FAILS: String(cleanupFails),
					MATERIALIZER_MODULE: new URL("../dist/index.mjs", import.meta.url)
						.href,
					ASSEMBLY_ROOT: assemblyRoot,
					PACKAGE_SELECTION: JSON.stringify(upgraded),
					ARCHIVE: archive.toString("base64"),
				},
				timeout: 10000,
				encoding: "utf8",
			},
		);
		expect(child.status, child.stderr).toBe(0);
		expect(
			(await readdir(assemblyRoot)).filter((name) =>
				name.startsWith(".staging-"),
			),
		).toHaveLength(cleanupFails ? 1 : 0);
		expect(await adapter.readCurrent()).toEqual(original);
		expect(
			await readFile(
				join(
					project(assemblyRoot, original.generationId),
					".agents/skills/workspace-summary/SKILL.md",
				),
				"utf8",
			),
		).toBe("# Summary\n");
		const retried = await adapter.materialize({ packages: [upgraded] });
		expect(await adapter.readCurrent()).toEqual(retried);
	},
	15000,
);
