import {
	agentApplications,
	agentAvailability,
	agentConfigurationRevisions,
	agentManagementHistory,
	agentOwners,
	agents,
	platformSecretRecords,
	retiredSecretWrappingKeys,
	secretKeyRotations,
	workloadReconciliations,
} from "./schema-agents";
import {
	fileReconciliation,
	platformFileAccesses,
	platformFiles,
	wecomConnections,
	wecomReceipts,
	wecomSetupSessions,
} from "./schema-channels-files";
import {
	conversationAuditEvents,
	conversationEvents,
	conversationExecutions,
	conversationMessages,
	conversationStops,
	conversations,
} from "./schema-conversations";
import {
	auditEvents,
	conversationGenerationTombstones,
	idempotencyRecords,
	outboxItems,
	persistedEvents,
	taskAuthorizationRecords,
	taskControlRecords,
} from "./schema-operations";

export {
	agentApplications,
	agentAvailability,
	agentConfigurationRevisions,
	agentManagementHistory,
	agentOwners,
	agents,
	platformSecretRecords,
	retiredSecretWrappingKeys,
	secretKeyRotations,
	workloadReconciliations,
} from "./schema-agents";
export {
	fileReconciliation,
	platformFileAccesses,
	platformFiles,
	wecomConnections,
	wecomReceipts,
	wecomSetupSessions,
} from "./schema-channels-files";
export {
	agentAvailabilityTargetType,
	agentDesiredState,
	agentFailureCode,
	agentManagementOperation,
	agentManagementStatus,
	agentManagementSubjectType,
	agentServiceAvailability,
	auditOutcome,
	conversationExecutionStatus,
	conversationMessageStatus,
	conversationStatus,
	conversationStopStatus,
	idempotencyStatus,
	outboxStatus,
	platformSchema,
	platformStatusValues,
	secretKeyRotationState,
} from "./schema-common";
export {
	conversationAuditEvents,
	conversationEvents,
	conversationExecutions,
	conversationMessages,
	conversationStops,
	conversations,
} from "./schema-conversations";
export {
	auditEvents,
	conversationGenerationTombstones,
	idempotencyRecords,
	outboxItems,
	persistedEvents,
	taskAuthorizationRecords,
	taskControlRecords,
} from "./schema-operations";

export const platformInfrastructureTables = [
	workloadReconciliations,
	agents,
	agentApplications,
	agentConfigurationRevisions,
	platformSecretRecords,
	secretKeyRotations,
	retiredSecretWrappingKeys,
	agentOwners,
	agentAvailability,
	agentManagementHistory,
	conversations,
	conversationExecutions,
	taskAuthorizationRecords,
	taskControlRecords,
	conversationGenerationTombstones,
	conversationMessages,
	conversationStops,
	conversationAuditEvents,
	conversationEvents,
	outboxItems,
	auditEvents,
	idempotencyRecords,
	persistedEvents,
	wecomReceipts,
	wecomConnections,
	wecomSetupSessions,
	platformFiles,
	platformFileAccesses,
	fileReconciliation,
] as const;
