/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectionConnectionsRouteImport } from './routes/connection.connections'
import { Route as ConnectionLoginRouteImport } from './routes/connection.login'
import { Route as ConnectionTokensRouteImport } from './routes/connection.tokens'
import { Route as ConnectionAdminAdministratorsRouteImport } from './routes/connection.admin.administrators'
import { Route as ConnectionAdminSharedConnectionsRouteImport } from './routes/connection.admin.shared-connections'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionConnectionsRoute = ConnectionConnectionsRouteImport.update({
  id: '/connection/connections',
  path: '/connection/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionLoginRoute = ConnectionLoginRouteImport.update({
  id: '/connection/login',
  path: '/connection/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionTokensRoute = ConnectionTokensRouteImport.update({
  id: '/connection/tokens',
  path: '/connection/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionAdminAdministratorsRoute =
  ConnectionAdminAdministratorsRouteImport.update({
    id: '/connection/admin/administrators',
    path: '/connection/admin/administrators',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectionAdminSharedConnectionsRoute =
  ConnectionAdminSharedConnectionsRouteImport.update({
    id: '/connection/admin/shared-connections',
    path: '/connection/admin/shared-connections',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connection/connections': typeof ConnectionConnectionsRoute
  '/connection/login': typeof ConnectionLoginRoute
  '/connection/tokens': typeof ConnectionTokensRoute
  '/connection/admin/administrators': typeof ConnectionAdminAdministratorsRoute
  '/connection/admin/shared-connections': typeof ConnectionAdminSharedConnectionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connection/connections': typeof ConnectionConnectionsRoute
  '/connection/login': typeof ConnectionLoginRoute
  '/connection/tokens': typeof ConnectionTokensRoute
  '/connection/admin/administrators': typeof ConnectionAdminAdministratorsRoute
  '/connection/admin/shared-connections': typeof ConnectionAdminSharedConnectionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connection/connections': typeof ConnectionConnectionsRoute
  '/connection/login': typeof ConnectionLoginRoute
  '/connection/tokens': typeof ConnectionTokensRoute
  '/connection/admin/administrators': typeof ConnectionAdminAdministratorsRoute
  '/connection/admin/shared-connections': typeof ConnectionAdminSharedConnectionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connection/connections'
    | '/connection/login'
    | '/connection/tokens'
    | '/connection/admin/administrators'
    | '/connection/admin/shared-connections'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connection/connections'
    | '/connection/login'
    | '/connection/tokens'
    | '/connection/admin/administrators'
    | '/connection/admin/shared-connections'
  id:
    | '__root__'
    | '/'
    | '/connection/connections'
    | '/connection/login'
    | '/connection/tokens'
    | '/connection/admin/administrators'
    | '/connection/admin/shared-connections'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionConnectionsRoute: typeof ConnectionConnectionsRoute
  ConnectionLoginRoute: typeof ConnectionLoginRoute
  ConnectionTokensRoute: typeof ConnectionTokensRoute
  ConnectionAdminAdministratorsRoute: typeof ConnectionAdminAdministratorsRoute
  ConnectionAdminSharedConnectionsRoute: typeof ConnectionAdminSharedConnectionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection/connections': {
      id: '/connection/connections'
      path: '/connection/connections'
      fullPath: '/connection/connections'
      preLoaderRoute: typeof ConnectionConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection/login': {
      id: '/connection/login'
      path: '/connection/login'
      fullPath: '/connection/login'
      preLoaderRoute: typeof ConnectionLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection/tokens': {
      id: '/connection/tokens'
      path: '/connection/tokens'
      fullPath: '/connection/tokens'
      preLoaderRoute: typeof ConnectionTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection/admin/administrators': {
      id: '/connection/admin/administrators'
      path: '/connection/admin/administrators'
      fullPath: '/connection/admin/administrators'
      preLoaderRoute: typeof ConnectionAdminAdministratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection/admin/shared-connections': {
      id: '/connection/admin/shared-connections'
      path: '/connection/admin/shared-connections'
      fullPath: '/connection/admin/shared-connections'
      preLoaderRoute: typeof ConnectionAdminSharedConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionConnectionsRoute: ConnectionConnectionsRoute,
  ConnectionLoginRoute: ConnectionLoginRoute,
  ConnectionTokensRoute: ConnectionTokensRoute,
  ConnectionAdminAdministratorsRoute: ConnectionAdminAdministratorsRoute,
  ConnectionAdminSharedConnectionsRoute: ConnectionAdminSharedConnectionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
