apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name | quote }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: runtime-legacy-migration
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  policyTypes: [Ingress, Egress]
  ingress: []
  egress: []
