import type { LiveVerificationEvidence } from "../test-project.ts";
import { githubV7LowRiskWriteScenarios } from "./github-v7-low-risk-write-scenarios.ts";

export const githubV7VerificationEvidence = {
	actionVersionIds: [
		"github.get_repository@v7",
		"github.list_branches@v7",
		"github.get_branch@v7",
		"github.list_commits@v7",
		"github.get_commit@v7",
		"github.compare_commits@v7",
		"github.get_commit_statuses@v7",
		"github.list_check_runs_for_ref@v7",
		"github.list_directory_contents@v7",
		"github.get_file_contents@v7",
		"github.search_repositories@v7",
		"github.search_commits@v7",
		"github.search_code@v7",
		"github.search_labels@v7",
		"github.search_topics@v7",
		"github.list_repository_forks@v7",
		"github.list_repository_tags@v7",
		"github.list_repository_languages@v7",
		"github.list_repository_contributors@v7",
		"github.list_repository_topics@v7",
		"github.get_repository_readme@v7",
		"github.list_repository_collaborators@v7",
		"github.get_repository_permission_for_user@v7",
		"github.get_ref@v7",
		"github.list_matching_refs@v7",
		"github.list_commit_comments@v7",
		"github.check_repository_starred@v7",
		"github.list_repository_stargazers@v7",
		"github.list_repository_watchers@v7",
		"github.list_repository_events@v7",
		"github.list_organization_repositories@v7",
		"github.list_repository_issues@v7",
		"github.get_issue@v7",
		"github.list_repository_labels@v7",
		"github.list_issue_labels@v7",
		"github.list_issue_comments@v7",
		"github.search_issues_and_pull_requests@v7",
		"github.list_pull_requests@v7",
		"github.list_pull_requests_associated_with_commit@v7",
		"github.list_pull_request_files@v7",
		"github.list_pull_request_commits@v7",
		"github.list_pull_request_requested_reviewers@v7",
		"github.list_pull_request_reviews@v7",
		"github.list_pull_request_review_comments@v7",
		"github.get_pull_request@v7",
		"github.check_pull_request_merged@v7",
		"github.list_issue_timeline_events@v7",
		"github.list_issue_events@v7",
		"github.list_repository_issue_events@v7",
		"github.list_milestones@v7",
		"github.get_milestone@v7",
		"github.get_issue_comment@v7",
		"github.get_label@v7",
		"github.list_assignees@v7",
		"github.list_repository_workflows@v7",
		"github.list_workflow_runs@v7",
		"github.get_workflow_run@v7",
		"github.list_workflow_run_jobs@v7",
		"github.list_releases@v7",
		"github.get_release@v7",
		"github.get_latest_release@v7",
		"github.get_release_by_tag@v7",
		"github.list_release_assets@v7",
		"github.get_workflow@v7",
		"github.list_workflow_run_artifacts@v7",
		"github.get_release_asset@v7",
		"github.get_current_user@v7",
		"github.list_my_repositories@v7",
		"github.list_public_events@v7",
		"github.list_user_public_events@v7",
		"github.list_user_received_public_events@v7",
		"github.list_authenticated_user_events@v7",
		"github.list_authenticated_user_received_events@v7",
		"github.search_users@v7",
		"github.get_user@v7",
		"github.list_user_repositories@v7",
		"github.list_my_starred_repositories@v7",
		"github.create_issue@v7",
		"github.update_issue@v7",
		"github.create_issue_comment@v7",
		"github.update_issue_comment@v7",
		"github.delete_issue_comment@v7",
		...githubV7LowRiskWriteScenarios.map(
			({ actionVersionId }) => actionVersionId,
		),
	],
	cleanup: "SUCCEEDED",
	containerId: "1369705971",
	externalAccount: "328682695",
	provider: "github",
	providerReleaseId:
		"github-openconnector-0cb0e0dd2ed686fa7fa2ff8d9eef97a7d6b31674-connection-v7",
	runId: "34929778284-1",
} as const satisfies LiveVerificationEvidence;
