import type { LiveVerificationEvidence } from "../test-project.ts";

const providerReleaseId =
	"github-openconnector-0cb0e0dd2ed686fa7fa2ff8d9eef97a7d6b31674-connection-v9";

export const githubV9PrimaryVerificationEvidence = {
	actionVersionIds: [
		"github.add_issue_assignees@v9",
		"github.add_issue_labels@v9",
		"github.check_pull_request_merged@v9",
		"github.check_repository_starred@v9",
		"github.clear_issue_labels@v9",
		"github.compare_commits@v9",
		"github.create_issue@v9",
		"github.create_issue_comment@v9",
		"github.create_label@v9",
		"github.create_milestone@v9",
		"github.create_or_update_file@v9",
		"github.create_pull_request@v9",
		"github.create_ref@v9",
		"github.create_release@v9",
		"github.delete_file@v9",
		"github.delete_issue_comment@v9",
		"github.delete_label@v9",
		"github.delete_milestone@v9",
		"github.delete_ref@v9",
		"github.delete_release@v9",
		"github.dismiss_pull_request_review@v9",
		"github.generate_release_notes@v9",
		"github.get_branch@v9",
		"github.get_commit@v9",
		"github.get_commit_statuses@v9",
		"github.get_current_user@v9",
		"github.get_file_contents@v9",
		"github.get_issue@v9",
		"github.get_issue_comment@v9",
		"github.get_label@v9",
		"github.get_latest_release@v9",
		"github.get_milestone@v9",
		"github.get_pull_request@v9",
		"github.get_ref@v9",
		"github.get_release@v9",
		"github.get_release_asset@v9",
		"github.get_release_by_tag@v9",
		"github.get_repository@v9",
		"github.get_repository_permission_for_user@v9",
		"github.get_repository_readme@v9",
		"github.get_user@v9",
		"github.get_workflow@v9",
		"github.get_workflow_run@v9",
		"github.list_assignees@v9",
		"github.list_authenticated_user_events@v9",
		"github.list_authenticated_user_received_events@v9",
		"github.list_branches@v9",
		"github.list_check_runs_for_ref@v9",
		"github.list_commit_comments@v9",
		"github.list_commits@v9",
		"github.list_directory_contents@v9",
		"github.list_issue_comments@v9",
		"github.list_issue_events@v9",
		"github.list_issue_labels@v9",
		"github.list_issue_timeline_events@v9",
		"github.list_matching_refs@v9",
		"github.list_milestones@v9",
		"github.list_my_repositories@v9",
		"github.list_my_starred_repositories@v9",
		"github.list_organization_repositories@v9",
		"github.list_public_events@v9",
		"github.list_pull_request_commits@v9",
		"github.list_pull_request_files@v9",
		"github.list_pull_request_requested_reviewers@v9",
		"github.list_pull_request_review_comments@v9",
		"github.list_pull_request_reviews@v9",
		"github.list_pull_requests@v9",
		"github.list_pull_requests_associated_with_commit@v9",
		"github.list_release_assets@v9",
		"github.list_releases@v9",
		"github.list_repository_collaborators@v9",
		"github.list_repository_contributors@v9",
		"github.list_repository_events@v9",
		"github.list_repository_forks@v9",
		"github.list_repository_issue_events@v9",
		"github.list_repository_issues@v9",
		"github.list_repository_labels@v9",
		"github.list_repository_languages@v9",
		"github.list_repository_stargazers@v9",
		"github.list_repository_tags@v9",
		"github.list_repository_topics@v9",
		"github.list_repository_watchers@v9",
		"github.list_repository_workflows@v9",
		"github.list_user_public_events@v9",
		"github.list_user_received_public_events@v9",
		"github.list_user_repositories@v9",
		"github.list_workflow_run_artifacts@v9",
		"github.list_workflow_run_jobs@v9",
		"github.list_workflow_runs@v9",
		"github.lock_issue@v9",
		"github.remove_issue_assignees@v9",
		"github.remove_issue_label@v9",
		"github.remove_pull_request_reviewers@v9",
		"github.rename_branch@v9",
		"github.replace_repository_topics@v9",
		"github.request_pull_request_reviewers@v9",
		"github.search_code@v9",
		"github.search_commits@v9",
		"github.search_issues_and_pull_requests@v9",
		"github.search_labels@v9",
		"github.search_repositories@v9",
		"github.search_topics@v9",
		"github.search_users@v9",
		"github.set_issue_labels@v9",
		"github.star_repository@v9",
		"github.unlock_issue@v9",
		"github.unstar_repository@v9",
		"github.update_issue@v9",
		"github.update_issue_comment@v9",
		"github.update_label@v9",
		"github.update_milestone@v9",
		"github.update_pull_request@v9",
		"github.update_pull_request_branch@v9",
		"github.update_ref@v9",
		"github.update_release@v9",
	],
	cleanup: "SUCCEEDED",
	containerId: "1369705971",
	externalAccount: "328682695",
	provider: "github",
	providerReleaseId,
	runId: "35230562309-1",
} as const satisfies LiveVerificationEvidence;

export const githubV9ReviewerVerificationEvidence = {
	actionVersionIds: [
		"github.create_pull_request_review@v9",
		"github.create_pull_request_review_comment@v9",
		"github.delete_pending_pull_request_review@v9",
		"github.delete_pull_request_review_comment@v9",
		"github.get_current_user@v9",
		"github.get_pull_request@v9",
		"github.get_pull_request_review@v9",
		"github.get_repository@v9",
		"github.list_pull_request_review_comments@v9",
		"github.list_pull_request_reviews@v9",
		"github.reply_pull_request_review_comment@v9",
		"github.submit_pull_request_review@v9",
		"github.update_pull_request_review_comment@v9",
	],
	cleanup: "SUCCEEDED",
	containerId: "1369705971",
	externalAccount: "329435106",
	provider: "github",
	providerReleaseId,
	runId: "35230562309-1",
} as const satisfies LiveVerificationEvidence;

export const githubV9CommitReactionVerificationEvidence = {
	actionVersionIds: [
		"github.create_commit_comment@v9",
		"github.create_commit_status@v9",
		"github.create_issue_comment_reaction@v9",
		"github.create_issue_reaction@v9",
	],
	cleanup: "SUCCEEDED",
	containerId: "1369705971",
	externalAccount: "328682695",
	provider: "github",
	providerReleaseId,
	runId: "35230974861-1",
} as const satisfies LiveVerificationEvidence;

export const githubV9MergeVerificationEvidence = {
	actionVersionIds: ["github.merge_branch@v9", "github.merge_pull_request@v9"],
	cleanup: "SUCCEEDED",
	containerId: "1369705971",
	externalAccount: "328682695",
	provider: "github",
	providerReleaseId,
	runId: "35231093375-1",
} as const satisfies LiveVerificationEvidence;

export const githubV9RepositoryLifecycleVerificationEvidence = {
	actionVersionIds: [
		"github.add_repository_collaborator@v9",
		"github.cancel_workflow_run@v9",
		"github.create_repository@v9",
		"github.delete_release_asset@v9",
		"github.delete_repository@v9",
		"github.disable_workflow@v9",
		"github.dispatch_workflow@v9",
		"github.enable_workflow@v9",
		"github.fork_repository@v9",
		"github.remove_repository_collaborator@v9",
		"github.rerun_failed_jobs@v9",
		"github.rerun_workflow@v9",
		"github.sync_fork_branch_with_upstream@v9",
		"github.update_repository@v9",
	],
	cleanup: "SUCCEEDED",
	containerId: "1369705971",
	externalAccount: "328682695",
	provider: "github",
	providerReleaseId,
	runId: "35231241395-1",
} as const satisfies LiveVerificationEvidence;

export const githubV9VerificationEvidenceRecords = [
	githubV9PrimaryVerificationEvidence,
	githubV9ReviewerVerificationEvidence,
	githubV9CommitReactionVerificationEvidence,
	githubV9MergeVerificationEvidence,
	githubV9RepositoryLifecycleVerificationEvidence,
] as const;
