import type { LiveVerificationEvidence } from "../test-project.ts";

const providerReleaseId =
	"github-openconnector-0cb0e0dd2ed686fa7fa2ff8d9eef97a7d6b31674-connection-v9";

export const githubV8PrimaryVerificationEvidence = {
	actionVersionIds: [
		"github.add_issue_assignees@v8",
		"github.add_issue_labels@v8",
		"github.check_pull_request_merged@v8",
		"github.check_repository_starred@v8",
		"github.clear_issue_labels@v8",
		"github.compare_commits@v8",
		"github.create_issue@v8",
		"github.create_issue_comment@v8",
		"github.create_label@v8",
		"github.create_milestone@v8",
		"github.create_or_update_file@v8",
		"github.create_pull_request@v8",
		"github.create_ref@v8",
		"github.create_release@v8",
		"github.delete_file@v8",
		"github.delete_issue_comment@v8",
		"github.delete_label@v8",
		"github.delete_milestone@v8",
		"github.delete_ref@v8",
		"github.delete_release@v8",
		"github.dismiss_pull_request_review@v8",
		"github.generate_release_notes@v8",
		"github.get_branch@v8",
		"github.get_commit@v8",
		"github.get_commit_statuses@v8",
		"github.get_current_user@v8",
		"github.get_file_contents@v8",
		"github.get_issue@v8",
		"github.get_issue_comment@v8",
		"github.get_label@v8",
		"github.get_latest_release@v8",
		"github.get_milestone@v8",
		"github.get_pull_request@v8",
		"github.get_ref@v8",
		"github.get_release@v8",
		"github.get_release_asset@v8",
		"github.get_release_by_tag@v8",
		"github.get_repository@v8",
		"github.get_repository_permission_for_user@v8",
		"github.get_repository_readme@v8",
		"github.get_user@v8",
		"github.get_workflow@v8",
		"github.get_workflow_run@v8",
		"github.list_assignees@v8",
		"github.list_authenticated_user_events@v8",
		"github.list_authenticated_user_received_events@v8",
		"github.list_branches@v8",
		"github.list_check_runs_for_ref@v8",
		"github.list_commit_comments@v8",
		"github.list_commits@v8",
		"github.list_directory_contents@v8",
		"github.list_issue_comments@v8",
		"github.list_issue_events@v8",
		"github.list_issue_labels@v8",
		"github.list_issue_timeline_events@v8",
		"github.list_matching_refs@v8",
		"github.list_milestones@v8",
		"github.list_my_repositories@v8",
		"github.list_my_starred_repositories@v8",
		"github.list_organization_repositories@v8",
		"github.list_public_events@v8",
		"github.list_pull_request_commits@v8",
		"github.list_pull_request_files@v8",
		"github.list_pull_request_requested_reviewers@v8",
		"github.list_pull_request_review_comments@v8",
		"github.list_pull_request_reviews@v8",
		"github.list_pull_requests@v8",
		"github.list_pull_requests_associated_with_commit@v8",
		"github.list_release_assets@v8",
		"github.list_releases@v8",
		"github.list_repository_collaborators@v8",
		"github.list_repository_contributors@v8",
		"github.list_repository_events@v8",
		"github.list_repository_forks@v8",
		"github.list_repository_issue_events@v8",
		"github.list_repository_issues@v8",
		"github.list_repository_labels@v8",
		"github.list_repository_languages@v8",
		"github.list_repository_stargazers@v8",
		"github.list_repository_tags@v8",
		"github.list_repository_topics@v8",
		"github.list_repository_watchers@v8",
		"github.list_repository_workflows@v8",
		"github.list_user_public_events@v8",
		"github.list_user_received_public_events@v8",
		"github.list_user_repositories@v8",
		"github.list_workflow_run_artifacts@v8",
		"github.list_workflow_run_jobs@v8",
		"github.list_workflow_runs@v8",
		"github.lock_issue@v8",
		"github.remove_issue_assignees@v8",
		"github.remove_issue_label@v8",
		"github.remove_pull_request_reviewers@v8",
		"github.rename_branch@v8",
		"github.replace_repository_topics@v8",
		"github.request_pull_request_reviewers@v8",
		"github.search_code@v8",
		"github.search_commits@v8",
		"github.search_issues_and_pull_requests@v8",
		"github.search_labels@v8",
		"github.search_repositories@v8",
		"github.search_topics@v8",
		"github.search_users@v8",
		"github.set_issue_labels@v8",
		"github.star_repository@v8",
		"github.unlock_issue@v8",
		"github.unstar_repository@v8",
		"github.update_issue@v8",
		"github.update_issue_comment@v8",
		"github.update_label@v8",
		"github.update_milestone@v8",
		"github.update_pull_request@v8",
		"github.update_pull_request_branch@v8",
		"github.update_ref@v8",
		"github.update_release@v8",
	],
	cleanup: "SUCCEEDED",
	containerId: "1369705971",
	externalAccount: "328682695",
	provider: "github",
	providerReleaseId,
	runId: "35230562309-1",
} as const satisfies LiveVerificationEvidence;

export const githubV8ReviewerVerificationEvidence = {
	actionVersionIds: [
		"github.create_pull_request_review@v8",
		"github.create_pull_request_review_comment@v8",
		"github.delete_pending_pull_request_review@v8",
		"github.delete_pull_request_review_comment@v8",
		"github.get_current_user@v8",
		"github.get_pull_request@v8",
		"github.get_pull_request_review@v8",
		"github.get_repository@v8",
		"github.list_pull_request_review_comments@v8",
		"github.list_pull_request_reviews@v8",
		"github.reply_pull_request_review_comment@v8",
		"github.submit_pull_request_review@v8",
		"github.update_pull_request_review_comment@v8",
	],
	cleanup: "SUCCEEDED",
	containerId: "1369705971",
	externalAccount: "329435106",
	provider: "github",
	providerReleaseId,
	runId: "35230562309-1",
} as const satisfies LiveVerificationEvidence;

export const githubV8CommitReactionVerificationEvidence = {
	actionVersionIds: [
		"github.create_commit_comment@v8",
		"github.create_commit_status@v8",
		"github.create_issue_comment_reaction@v8",
		"github.create_issue_reaction@v8",
	],
	cleanup: "SUCCEEDED",
	containerId: "1369705971",
	externalAccount: "328682695",
	provider: "github",
	providerReleaseId,
	runId: "35230974861-1",
} as const satisfies LiveVerificationEvidence;

export const githubV8MergeVerificationEvidence = {
	actionVersionIds: ["github.merge_branch@v8", "github.merge_pull_request@v8"],
	cleanup: "SUCCEEDED",
	containerId: "1369705971",
	externalAccount: "328682695",
	provider: "github",
	providerReleaseId,
	runId: "35231093375-1",
} as const satisfies LiveVerificationEvidence;

export const githubV8RepositoryLifecycleVerificationEvidence = {
	actionVersionIds: [
		"github.add_repository_collaborator@v8",
		"github.cancel_workflow_run@v8",
		"github.create_repository@v8",
		"github.delete_release_asset@v8",
		"github.delete_repository@v8",
		"github.disable_workflow@v8",
		"github.dispatch_workflow@v8",
		"github.enable_workflow@v8",
		"github.fork_repository@v8",
		"github.remove_repository_collaborator@v8",
		"github.rerun_failed_jobs@v8",
		"github.rerun_workflow@v8",
		"github.sync_fork_branch_with_upstream@v8",
		"github.update_repository@v8",
	],
	cleanup: "SUCCEEDED",
	containerId: "1369705971",
	externalAccount: "328682695",
	provider: "github",
	providerReleaseId,
	runId: "35231241395-1",
} as const satisfies LiveVerificationEvidence;

export const githubV8VerificationEvidenceRecords = [
	githubV8PrimaryVerificationEvidence,
	githubV8ReviewerVerificationEvidence,
	githubV8CommitReactionVerificationEvidence,
	githubV8MergeVerificationEvidence,
	githubV8RepositoryLifecycleVerificationEvidence,
] as const;
